<?php return array(
    'root' => array(
        'name' => 'neos/neos-base-distribution',
        'pretty_version' => '8.1.1',
        'version' => '8.1.1.0',
        'reference' => NULL,
        'type' => 'project',
        'install_path' => __DIR__ . '/../../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'behat/transliterator' => array(
            'pretty_version' => 'v1.5.0',
            'version' => '1.5.0.0',
            'reference' => 'baac5873bac3749887d28ab68e2f74db3a4408af',
            'type' => 'library',
            'install_path' => __DIR__ . '/../behat/transliterator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'brick/math' => array(
            'pretty_version' => '0.10.2',
            'version' => '0.10.2.0',
            'reference' => '459f2781e1a08d52ee56b0b1444086e038561e3f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../brick/math',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/ca-bundle' => array(
            'pretty_version' => '1.3.3',
            'version' => '1.3.3.0',
            'reference' => '30897edbfb15e784fe55587b4f73ceefd3c4d98c',
            'type' => 'library',
            'install_path' => __DIR__ . '/./ca-bundle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/class-map-generator' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => '1e1cb2b791facb2dfe32932a7718cf2571187513',
            'type' => 'library',
            'install_path' => __DIR__ . '/./class-map-generator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/composer' => array(
            'pretty_version' => '2.4.2',
            'version' => '2.4.2.0',
            'reference' => '7d887621e69a0311eb50aed4a16f7044b2b385b9',
            'type' => 'library',
            'install_path' => __DIR__ . '/./composer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/metadata-minifier' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => 'c549d23829536f0d0e984aaabbf02af91f443207',
            'type' => 'library',
            'install_path' => __DIR__ . '/./metadata-minifier',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/pcre' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => 'e300eb6c535192decd27a85bc72a9290f0d6b3bd',
            'type' => 'library',
            'install_path' => __DIR__ . '/./pcre',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/semver' => array(
            'pretty_version' => '3.3.2',
            'version' => '3.3.2.0',
            'reference' => '3953f23262f2bff1919fc82183ad9acb13ff62c9',
            'type' => 'library',
            'install_path' => __DIR__ . '/./semver',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/spdx-licenses' => array(
            'pretty_version' => '1.5.7',
            'version' => '1.5.7.0',
            'reference' => 'c848241796da2abf65837d51dce1fae55a960149',
            'type' => 'library',
            'install_path' => __DIR__ . '/./spdx-licenses',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/xdebug-handler' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'reference' => 'ced299686f41dce890debac69273b47ffe98a40c',
            'type' => 'library',
            'install_path' => __DIR__ . '/./xdebug-handler',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/annotations' => array(
            'pretty_version' => '1.13.3',
            'version' => '1.13.3.0',
            'reference' => '648b0343343565c4a056bfc8392201385e8d89f0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/annotations',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/cache' => array(
            'pretty_version' => '2.2.0',
            'version' => '2.2.0.0',
            'reference' => '1ca8f21980e770095a31456042471a57bc4c68fb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/collections' => array(
            'pretty_version' => '1.7.3',
            'version' => '1.7.3.0',
            'reference' => '09dde3eb237756190f2de738d3c97cff10a8407b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/collections',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/common' => array(
            'pretty_version' => '3.4.0',
            'version' => '3.4.0.0',
            'reference' => 'e09556bbdf95b8420e649162b19ae9da2d1a80f3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/common',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/dbal' => array(
            'pretty_version' => '2.13.9',
            'version' => '2.13.9.0',
            'reference' => 'c480849ca3ad6706a39c970cdfe6888fa8a058b8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/dbal',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/deprecations' => array(
            'pretty_version' => 'v0.5.3',
            'version' => '0.5.3.0',
            'reference' => '9504165960a1f83cc1480e2be1dd0a0478561314',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/deprecations',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/event-manager' => array(
            'pretty_version' => '1.1.2',
            'version' => '1.1.2.0',
            'reference' => 'eb2ecf80e3093e8f3c2769ac838e27d8ede8e683',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/event-manager',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/inflector' => array(
            'pretty_version' => '2.0.5',
            'version' => '2.0.5.0',
            'reference' => 'ade2b3bbfb776f27f0558e26eed43b5d9fe1b392',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/inflector',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/instantiator' => array(
            'pretty_version' => '1.4.1',
            'version' => '1.4.1.0',
            'reference' => '10dcfce151b967d20fde1b34ae6640712c3891bc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/instantiator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/lexer' => array(
            'pretty_version' => '1.2.3',
            'version' => '1.2.3.0',
            'reference' => 'c268e882d4dbdd85e36e4ad69e02dc284f89d229',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/lexer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/migrations' => array(
            'pretty_version' => '3.4.2',
            'version' => '3.4.2.0',
            'reference' => 'f9b4c8032276460afd9dfa62fb215734b4380d90',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/migrations',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/orm' => array(
            'pretty_version' => '2.13.1',
            'version' => '2.13.1.0',
            'reference' => '35c44a56677adb3ce796138b6e4934ce93ec6811',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/orm',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/persistence' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'reference' => 'ac6fce61f037d7e54dbb2435f5b5648d86548e23',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/persistence',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'egulias/email-validator' => array(
            'pretty_version' => '3.2.1',
            'version' => '3.2.1.0',
            'reference' => 'f88dcf4b14af14a98ad96b14b2b317969eab6715',
            'type' => 'library',
            'install_path' => __DIR__ . '/../egulias/email-validator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'flowpack/behat' => array(
            'dev_requirement' => true,
            'replaced' => array(
                0 => '8.1.0',
            ),
        ),
        'friendsofphp/proxy-manager-lts' => array(
            'pretty_version' => 'v1.0.12',
            'version' => '1.0.12.0',
            'reference' => '8419f0158715b30d4b99a5bd37c6a39671994ad7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../friendsofphp/proxy-manager-lts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'gedmo/doctrine-extensions' => array(
            'pretty_version' => 'v3.8.0',
            'version' => '3.8.0.0',
            'reference' => '4ba5377b1a1d9a988205c4e37f5d5287eb8ebd28',
            'type' => 'library',
            'install_path' => __DIR__ . '/../gedmo/doctrine-extensions',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/guzzle' => array(
            'pretty_version' => '7.5.0',
            'version' => '7.5.0.0',
            'reference' => 'b50a2a1251152e43f6a37f0fa053e730a67d25ba',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/guzzle',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'guzzlehttp/promises' => array(
            'pretty_version' => '1.5.2',
            'version' => '1.5.2.0',
            'reference' => 'b94b2807d85443f9719887892882d0329d1e2598',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/promises',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'guzzlehttp/psr7' => array(
            'pretty_version' => '2.4.1',
            'version' => '2.4.1.0',
            'reference' => '69568e4293f4fa993f3b0e51c9723e1e17c41379',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/psr7',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'imagine/imagine' => array(
            'pretty_version' => '1.3.2',
            'version' => '1.3.2.0',
            'reference' => 'ae864f26afbf8859ebd2e2b9df92d77ee175dc13',
            'type' => 'library',
            'install_path' => __DIR__ . '/../imagine/imagine',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'justinrainbow/json-schema' => array(
            'pretty_version' => '5.2.12',
            'version' => '5.2.12.0',
            'reference' => 'ad87d5a5ca981228e0e205c2bc7dfb8e24559b60',
            'type' => 'library',
            'install_path' => __DIR__ . '/../justinrainbow/json-schema',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-code' => array(
            'pretty_version' => '4.7.0',
            'version' => '4.7.0.0',
            'reference' => '0337d9265bc2e6376babad8c511500821620cb30',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-code',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'league/csv' => array(
            'pretty_version' => '9.8.0',
            'version' => '9.8.0.0',
            'reference' => '9d2e0265c5d90f5dd601bc65ff717e05cec19b47',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/csv',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mikey179/vfsstream' => array(
            'pretty_version' => 'v1.6.11',
            'version' => '1.6.11.0',
            'reference' => '17d16a85e6c26ce1f3e2fa9ceeacdc2855db1e9f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mikey179/vfsstream',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'myclabs/deep-copy' => array(
            'pretty_version' => '1.11.0',
            'version' => '1.11.0.0',
            'reference' => '14daed4296fae74d9e3201d2c4925d1acb7aa614',
            'type' => 'library',
            'install_path' => __DIR__ . '/../myclabs/deep-copy',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'neos/behat' => array(
            'pretty_version' => '8.1.0',
            'version' => '8.1.0.0',
            'reference' => '471be8a0617bc190b33d513cfcb93773ec6f91c6',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.Behat',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'neos/buildessentials' => array(
            'pretty_version' => '8.1.0',
            'version' => '8.1.0.0',
            'reference' => '3e8ea81865adb6781c16f2085bb27c35a3a274ce',
            'type' => 'neos-build',
            'install_path' => __DIR__ . '/../../../Build/BuildEssentials',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'neos/cache' => array(
            'pretty_version' => '8.1.1',
            'version' => '8.1.1.0',
            'reference' => 'aea74ed56e3ee0128c35213127b28d67dfc632c2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../neos/cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/cli-setup' => array(
            'pretty_version' => '8.1.1',
            'version' => '8.1.1.0',
            'reference' => '37e85410cec409418928df92a61bb0603bf249b9',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.CliSetup',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/composer-plugin' => array(
            'pretty_version' => '2.1.3',
            'version' => '2.1.3.0',
            'reference' => '6f148a5c61bb9b5f03f064c1f74829381c3fdaca',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../neos/composer-plugin',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/content-repository' => array(
            'pretty_version' => '8.1.1',
            'version' => '8.1.1.0',
            'reference' => 'c46f5dd52827748d50813d3b1e184b41276dc8dd',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.ContentRepository',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/demo' => array(
            'pretty_version' => '8.1.1',
            'version' => '8.1.1.0',
            'reference' => '9af15d8a351adcf6f1fc347e1b0ae70d9aa3ce10',
            'type' => 'neos-site',
            'install_path' => __DIR__ . '/../../Sites/Neos.Demo',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/diff' => array(
            'pretty_version' => '8.1.1',
            'version' => '8.1.1.0',
            'reference' => '3e17859e5ef1dbf2754820ffcb0571bf37662745',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.Diff',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/eel' => array(
            'pretty_version' => '8.1.1',
            'version' => '8.1.1.0',
            'reference' => '8f46fcf77119c5d59149ab22000ed88259914802',
            'type' => 'neos-framework',
            'install_path' => __DIR__ . '/../../Framework/Neos.Eel',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/error-messages' => array(
            'pretty_version' => '8.1.1',
            'version' => '8.1.1.0',
            'reference' => '6ab4242b86bbe64b3f746ecca3da0d2133ed2968',
            'type' => 'library',
            'install_path' => __DIR__ . '/../neos/error-messages',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/flow' => array(
            'pretty_version' => '8.1.1',
            'version' => '8.1.1.0',
            'reference' => '8da3b2128841b6d5110ca53558607e3dc92ad951',
            'type' => 'neos-framework',
            'install_path' => __DIR__ . '/../../Framework/Neos.Flow',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/flow-log' => array(
            'pretty_version' => '8.1.1',
            'version' => '8.1.1.0',
            'reference' => 'fe3d8bb5d48951077868359c67c8d42b480c4da9',
            'type' => 'package',
            'install_path' => __DIR__ . '/../neos/flow-log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/fluid-adaptor' => array(
            'pretty_version' => '8.1.1',
            'version' => '8.1.1.0',
            'reference' => '58ae32e08738c1c080ccb70a0df20a94cd0877c7',
            'type' => 'neos-framework',
            'install_path' => __DIR__ . '/../../Framework/Neos.FluidAdaptor',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/form' => array(
            'pretty_version' => '5.3.3',
            'version' => '5.3.3.0',
            'reference' => '97828f1b7428ea0532b71337599dba24f429e04e',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.Form',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/fusion' => array(
            'pretty_version' => '8.1.1',
            'version' => '8.1.1.0',
            'reference' => '60d12f88cc04d9d2d6be25973793b7941994cd4b',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.Fusion',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/fusion-afx' => array(
            'pretty_version' => '8.1.1',
            'version' => '8.1.1.0',
            'reference' => 'd769737ec6cccfaa5b628c01a975d2b00ea54cef',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.Fusion.Afx',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/fusion-form' => array(
            'pretty_version' => 'v2.0.11',
            'version' => '2.0.11.0',
            'reference' => '0f49cccb4a3fe199b33be97c0607261882c7a279',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.Fusion.Form',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/http-factories' => array(
            'pretty_version' => '8.1.1',
            'version' => '8.1.1.0',
            'reference' => '0f8e314ae6a6ff74fe0e41133478bdcd166c09ac',
            'type' => 'neos-framework',
            'install_path' => __DIR__ . '/../../Framework/Neos.Http.Factories',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/imagine' => array(
            'pretty_version' => '3.3.0',
            'version' => '3.3.0.0',
            'reference' => '25c1fcd717f914e0d036b56c6f40d5853a16e549',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.Imagine',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/kickstarter' => array(
            'pretty_version' => '8.1.1',
            'version' => '8.1.1.0',
            'reference' => 'c52a720fc7658ff748e5ff962d62bd6c8f967659',
            'type' => 'neos-framework',
            'install_path' => __DIR__ . '/../../Framework/Neos.Kickstarter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/media' => array(
            'pretty_version' => '8.1.1',
            'version' => '8.1.1.0',
            'reference' => '8b8c228c4e87b8a3c8adc04c4ff1a8fc90ee19fc',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.Media',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/media-browser' => array(
            'pretty_version' => '8.1.1',
            'version' => '8.1.1.0',
            'reference' => '813b2c57be1e87d722b6bdac672a345c3323ee82',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.Media.Browser',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/neos' => array(
            'pretty_version' => '8.1.1',
            'version' => '8.1.1.0',
            'reference' => '582f0e1b647b0cda62736e9b1f178c5ff14adc08',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.Neos',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/neos-base-distribution' => array(
            'pretty_version' => '8.1.1',
            'version' => '8.1.1.0',
            'reference' => NULL,
            'type' => 'project',
            'install_path' => __DIR__ . '/../../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/neos-setup' => array(
            'pretty_version' => '1.1.7',
            'version' => '1.1.7.0',
            'reference' => '3848c476ba480878291cd7ddc58fbccd93a7c37a',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.Neos.Setup',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/neos-ui' => array(
            'pretty_version' => '8.1.0',
            'version' => '8.1.0.0',
            'reference' => '91f51c99e844c8cd72bcc775f0069f2257e202af',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.Neos.Ui',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/neos-ui-compiled' => array(
            'pretty_version' => '8.1.0',
            'version' => '8.1.0.0',
            'reference' => '79f9d1687a3f722e24de5061e42648790d7e80c6',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.Neos.Ui.Compiled',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/nodetypes-assetlist' => array(
            'pretty_version' => '8.1.1',
            'version' => '8.1.1.0',
            'reference' => 'c03334adb891e83c0910f9a6d882e5ced893b39d',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.NodeTypes.AssetList',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/nodetypes-basemixins' => array(
            'pretty_version' => '8.1.1',
            'version' => '8.1.1.0',
            'reference' => '88137eb84876ac8217215254d73bf5db537cdfed',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.NodeTypes.BaseMixins',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/nodetypes-contentreferences' => array(
            'pretty_version' => '8.1.1',
            'version' => '8.1.1.0',
            'reference' => '523aa7220b1be2f2f87dc826952b2c9e23ad296d',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.NodeTypes.ContentReferences',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/nodetypes-html' => array(
            'pretty_version' => '8.1.1',
            'version' => '8.1.1.0',
            'reference' => '0214ed11a990a1f16cf67e43e2501114c5e18739',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.NodeTypes.Html',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/nodetypes-navigation' => array(
            'pretty_version' => '8.1.1',
            'version' => '8.1.1.0',
            'reference' => 'd80290cb0da14e2a8cf37872a928fdcdad0a8e4a',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.NodeTypes.Navigation',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/party' => array(
            'pretty_version' => '7.0.1',
            'version' => '7.0.1.0',
            'reference' => '947d85442aa91877227a64c19ab76fbaff497b31',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.Party',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/redirecthandler' => array(
            'pretty_version' => '5.0.3',
            'version' => '5.0.3.0',
            'reference' => 'fa24ecd1b951d0c8e388027f5f459f89a0e29230',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.RedirectHandler',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/redirecthandler-databasestorage' => array(
            'pretty_version' => '5.0.2',
            'version' => '5.0.2.0',
            'reference' => 'f8e5ea19d09aa4317172908ffcfceb3924773e8b',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.RedirectHandler.DatabaseStorage',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/redirecthandler-neosadapter' => array(
            'pretty_version' => '4.3.1',
            'version' => '4.3.1.0',
            'reference' => '7009c8d653ad205344dd9dfa9b2fd6638e2ffe8d',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.RedirectHandler.NeosAdapter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/redirecthandler-storageimplementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '3.0',
            ),
        ),
        'neos/redirecthandler-ui' => array(
            'pretty_version' => '2.4.6',
            'version' => '2.4.6.0',
            'reference' => '9ca66d4854b9d9341dffdb24f82185d0000238f3',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.RedirectHandler.Ui',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/seo' => array(
            'pretty_version' => '3.3.3',
            'version' => '3.3.3.0',
            'reference' => '25d71abad249abf398bc0b72bbe5ae3dd84a9c8d',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.Seo',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/setup' => array(
            'pretty_version' => '5.0.0',
            'version' => '5.0.0.0',
            'reference' => '2fd9b320ed455c0496a3b4f6db2b786baa9ffb4f',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.Setup',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/site-kickstarter' => array(
            'pretty_version' => '8.1.1',
            'version' => '8.1.1.0',
            'reference' => '9a259aa2f73ee26970438a8ab4ccbbb05889c5c9',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.SiteKickstarter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/twitter-bootstrap' => array(
            'pretty_version' => '3.0.7',
            'version' => '3.0.7.0',
            'reference' => '124c5903793d3fb05bb6e0d94157d51d56a5061e',
            'type' => 'neos-package',
            'install_path' => __DIR__ . '/../../Application/Neos.Twitter.Bootstrap',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/utility-arrays' => array(
            'pretty_version' => '8.1.1',
            'version' => '8.1.1.0',
            'reference' => '018285aeddcb4a882065ff8ddc30fd8676d35ec2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../neos/utility-arrays',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/utility-files' => array(
            'pretty_version' => '8.1.1',
            'version' => '8.1.1.0',
            'reference' => '10f3067016960c51e5f6cdb4940ca444c7ff9b7e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../neos/utility-files',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/utility-mediatypes' => array(
            'pretty_version' => '8.1.1',
            'version' => '8.1.1.0',
            'reference' => '236f4e758c6a8395bbe6919b45d331b88ac6860f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../neos/utility-mediatypes',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/utility-objecthandling' => array(
            'pretty_version' => '8.1.1',
            'version' => '8.1.1.0',
            'reference' => 'c1b2554a03c722fa77ef7fa24a5707a7c3677c12',
            'type' => 'library',
            'install_path' => __DIR__ . '/../neos/utility-objecthandling',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/utility-opcodecache' => array(
            'pretty_version' => '8.1.1',
            'version' => '8.1.1.0',
            'reference' => '2c6825a64ba87f87100124e1c1eb6e77723fd3d0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../neos/utility-opcodecache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/utility-pdo' => array(
            'pretty_version' => '8.1.1',
            'version' => '8.1.1.0',
            'reference' => '45487bed859af049d60d1ee8952c79f00740ab97',
            'type' => 'library',
            'install_path' => __DIR__ . '/../neos/utility-pdo',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/utility-schema' => array(
            'pretty_version' => '8.1.1',
            'version' => '8.1.1.0',
            'reference' => '8dabf7798928b8286fad43706e8cba9164d34b93',
            'type' => 'library',
            'install_path' => __DIR__ . '/../neos/utility-schema',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neos/utility-unicode' => array(
            'pretty_version' => '8.1.1',
            'version' => '8.1.1.0',
            'reference' => 'cfc72b461edaf7b8006e730dd5cb3a8943950787',
            'type' => 'library',
            'install_path' => __DIR__ . '/../neos/utility-unicode',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'nikic/php-parser' => array(
            'pretty_version' => 'v4.15.1',
            'version' => '4.15.1.0',
            'reference' => '0ef6c55a3f47f89d7a374e6f835197a0b5fcf900',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nikic/php-parser',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'ocramius/proxy-manager' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '^2.1',
            ),
        ),
        'packagefactory/atomicfusion-afx' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'phar-io/manifest' => array(
            'pretty_version' => '2.0.3',
            'version' => '2.0.3.0',
            'reference' => '97803eca37d319dfa7826cc2437fc020857acb53',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phar-io/manifest',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phar-io/version' => array(
            'pretty_version' => '3.2.1',
            'version' => '3.2.1.0',
            'reference' => '4f7fd7836c6f332bb2933569e566a0d6c4cbed74',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phar-io/version',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-code-coverage' => array(
            'pretty_version' => '9.2.17',
            'version' => '9.2.17.0',
            'reference' => 'aa94dc41e8661fe90c7316849907cba3007b10d8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-code-coverage',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-file-iterator' => array(
            'pretty_version' => '3.0.6',
            'version' => '3.0.6.0',
            'reference' => 'cf1c2e7c203ac650e352f4cc675a7021e7d1b3cf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-file-iterator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-invoker' => array(
            'pretty_version' => '3.1.1',
            'version' => '3.1.1.0',
            'reference' => '5a10147d0aaf65b58940a0b72f71c9ac0423cc67',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-invoker',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-text-template' => array(
            'pretty_version' => '2.0.4',
            'version' => '2.0.4.0',
            'reference' => '5da5f67fc95621df9ff4c4e5a84d6a8a2acf7c28',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-text-template',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-timer' => array(
            'pretty_version' => '5.0.3',
            'version' => '5.0.3.0',
            'reference' => '5a63ce20ed1b5bf577850e2c4e87f4aa902afbd2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-timer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/phpunit' => array(
            'pretty_version' => '9.5.24',
            'version' => '9.5.24.0',
            'reference' => 'd0aa6097bef9fd42458a9b3c49da32c6ce6129c5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/phpunit',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'psr/cache' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => 'aa5030cfa5405eccfdcb1083ce040c2cb8d253bf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/cache-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '2.0.0 || 3.0.0',
                1 => '2.0|3.0',
            ),
        ),
        'psr/container' => array(
            'pretty_version' => '1.1.2',
            'version' => '1.1.2.0',
            'reference' => '513e0666f7216c7459170d56df27dfcefe1689ea',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-client' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => '2dfb5f6c5eff0e91e20e913f8c5452ed95b86621',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-client',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-client-implementation' => array(
            'dev_requirement' => true,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-factory' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => '12ac7fcd07e5b077433f5f2bee95b3a771bf61be',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-factory',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-factory-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-message' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => 'f6561bf28d520154e4b0ec72be95418abe6d9363',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-server-handler' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => 'aff2f80e33b7f026ec96bb42f63242dc50ffcae7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-server-handler',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-server-middleware' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => '2296f45510945530b9dceb8bcedb5cb84d40c5f5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-server-middleware',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'reference' => 'ef29f6d262798707a9edd554e2b82517ef3a9376',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0|2.0',
                1 => '2.0.0 || 3.0.0',
            ),
        ),
        'psr/simple-cache' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => '764e0b3939f5ca87cb904f570ef9be2d78a07865',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/simple-cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/simple-cache-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '2.0.0 || 3.0.0',
                1 => '1.0|2.0|3.0',
            ),
        ),
        'ralouphie/getallheaders' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'reference' => '120b605dfeb996808c31b6477290a714d356e822',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ralouphie/getallheaders',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ramsey/collection' => array(
            'pretty_version' => '1.2.2',
            'version' => '1.2.2.0',
            'reference' => 'cccc74ee5e328031b15640b51056ee8d3bb66c0a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ramsey/collection',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ramsey/uuid' => array(
            'pretty_version' => '4.5.1',
            'version' => '4.5.1.0',
            'reference' => 'a161a26d917604dc6d3aa25100fddf2556e9f35d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ramsey/uuid',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'react/promise' => array(
            'pretty_version' => 'v2.9.0',
            'version' => '2.9.0.0',
            'reference' => '234f8fd1023c9158e2314fa9d7d0e6a83db42910',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/promise',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'rhumsaa/uuid' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '4.5.1',
            ),
        ),
        'sebastian/cli-parser' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => '442e7c7e687e42adc03470c7b668bc4b2402c0b2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/cli-parser',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/code-unit' => array(
            'pretty_version' => '1.0.8',
            'version' => '1.0.8.0',
            'reference' => '1fc9f64c0927627ef78ba436c9b17d967e68e120',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/code-unit',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/code-unit-reverse-lookup' => array(
            'pretty_version' => '2.0.3',
            'version' => '2.0.3.0',
            'reference' => 'ac91f01ccec49fb77bdc6fd1e548bc70f7faa3e5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/code-unit-reverse-lookup',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/comparator' => array(
            'pretty_version' => '4.0.8',
            'version' => '4.0.8.0',
            'reference' => 'fa0f136dd2334583309d32b62544682ee972b51a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/comparator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/complexity' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'reference' => '739b35e53379900cc9ac327b2147867b8b6efd88',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/complexity',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/diff' => array(
            'pretty_version' => '4.0.4',
            'version' => '4.0.4.0',
            'reference' => '3461e3fccc7cfdfc2720be910d3bd73c69be590d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/diff',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/environment' => array(
            'pretty_version' => '5.1.4',
            'version' => '5.1.4.0',
            'reference' => '1b5dff7bb151a4db11d49d90e5408e4e938270f7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/environment',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/exporter' => array(
            'pretty_version' => '4.0.5',
            'version' => '4.0.5.0',
            'reference' => 'ac230ed27f0f98f597c8a2b6eb7ac563af5e5b9d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/exporter',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/global-state' => array(
            'pretty_version' => '5.0.5',
            'version' => '5.0.5.0',
            'reference' => '0ca8db5a5fc9c8646244e629625ac486fa286bf2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/global-state',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/lines-of-code' => array(
            'pretty_version' => '1.0.3',
            'version' => '1.0.3.0',
            'reference' => 'c1c2e997aa3146983ed888ad08b15470a2e22ecc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/lines-of-code',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/object-enumerator' => array(
            'pretty_version' => '4.0.4',
            'version' => '4.0.4.0',
            'reference' => '5c9eeac41b290a3712d88851518825ad78f45c71',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/object-enumerator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/object-reflector' => array(
            'pretty_version' => '2.0.4',
            'version' => '2.0.4.0',
            'reference' => 'b4f479ebdbf63ac605d183ece17d8d7fe49c15c7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/object-reflector',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/recursion-context' => array(
            'pretty_version' => '4.0.4',
            'version' => '4.0.4.0',
            'reference' => 'cd9d8cf3c5804de4341c283ed787f099f5506172',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/recursion-context',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/resource-operations' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'reference' => '0f4443cb3a1d92ce809899753bc0d5d5a8dd19a8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/resource-operations',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/type' => array(
            'pretty_version' => '3.2.0',
            'version' => '3.2.0.0',
            'reference' => 'fb3fe09c5f0bae6bc27ef3ce933a1e0ed9464b6e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/type',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/version' => array(
            'pretty_version' => '3.0.2',
            'version' => '3.0.2.0',
            'reference' => 'c6c1022351a901512170118436c764e473f6de8c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/version',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'seld/jsonlint' => array(
            'pretty_version' => '1.9.0',
            'version' => '1.9.0.0',
            'reference' => '4211420d25eba80712bff236a98960ef68b866b7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../seld/jsonlint',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'seld/phar-utils' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'reference' => 'ea2f4014f163c1be4c601b9b7bd6af81ba8d701c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../seld/phar-utils',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'seld/signal-handler' => array(
            'pretty_version' => '2.0.1',
            'version' => '2.0.1.0',
            'reference' => 'f69d119511dc0360440cdbdaa71829c149b7be75',
            'type' => 'library',
            'install_path' => __DIR__ . '/../seld/signal-handler',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/cache' => array(
            'pretty_version' => 'v6.1.3',
            'version' => '6.1.3.0',
            'reference' => '5cf8e75f02932818889e0609380b8d5427a6c86c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/cache-contracts' => array(
            'pretty_version' => 'v3.1.1',
            'version' => '3.1.1.0',
            'reference' => '2eab7fa459af6d75c6463e63e633b667a9b761d3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/cache-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/cache-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.1|2.0|3.0',
            ),
        ),
        'symfony/console' => array(
            'pretty_version' => 'v5.4.12',
            'version' => '5.4.12.0',
            'reference' => 'c072aa8f724c3af64e2c7a96b796a4863d24dba1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/console',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/css-selector' => array(
            'pretty_version' => 'v2.8.52',
            'version' => '2.8.52.0',
            'reference' => '7b1692e418d7ccac24c373528453bc90e42797de',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/css-selector',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/deprecation-contracts' => array(
            'pretty_version' => 'v3.1.1',
            'version' => '3.1.1.0',
            'reference' => '07f1b9cc2ffee6aaafcf4b710fbc38ff736bd918',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/deprecation-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/dom-crawler' => array(
            'pretty_version' => 'v5.4.12',
            'version' => '5.4.12.0',
            'reference' => '291c1e92281a09152dda089f782e23dedd34bd4f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/dom-crawler',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/filesystem' => array(
            'pretty_version' => 'v6.1.4',
            'version' => '6.1.4.0',
            'reference' => '3f39c04d2630c34019907b02f85672dac99f8659',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/filesystem',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/finder' => array(
            'pretty_version' => 'v6.1.3',
            'version' => '6.1.3.0',
            'reference' => '39696bff2c2970b3779a5cac7bf9f0b88fc2b709',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/finder',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-ctype' => array(
            'pretty_version' => 'v1.26.0',
            'version' => '1.26.0.0',
            'reference' => '6fd1b9a79f6e3cf65f9e679b23af304cd9e010d4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-ctype',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-grapheme' => array(
            'pretty_version' => 'v1.26.0',
            'version' => '1.26.0.0',
            'reference' => '433d05519ce6990bf3530fba6957499d327395c2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-grapheme',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-idn' => array(
            'pretty_version' => 'v1.26.0',
            'version' => '1.26.0.0',
            'reference' => '59a8d271f00dd0e4c2e518104cc7963f655a1aa8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-idn',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-normalizer' => array(
            'pretty_version' => 'v1.26.0',
            'version' => '1.26.0.0',
            'reference' => '219aa369ceff116e673852dce47c3a41794c14bd',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-normalizer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'symfony/polyfill-php70' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'symfony/polyfill-php71' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'symfony/polyfill-php72' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'symfony/polyfill-php73' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'symfony/polyfill-php74' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'symfony/polyfill-php80' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'symfony/polyfill-php81' => array(
            'pretty_version' => 'v1.26.0',
            'version' => '1.26.0.0',
            'reference' => '13f6d1271c663dc5ae9fb843a8f16521db7687a1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php81',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/process' => array(
            'pretty_version' => 'v6.1.3',
            'version' => '6.1.3.0',
            'reference' => 'a6506e99cfad7059b1ab5cab395854a0a0c21292',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/process',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/service-contracts' => array(
            'pretty_version' => 'v2.5.2',
            'version' => '2.5.2.0',
            'reference' => '4b426aac47d6427cc1a1d0f7e2ac724627f5966c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/service-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/stopwatch' => array(
            'pretty_version' => 'v6.1.0',
            'version' => '6.1.0.0',
            'reference' => '77dedae82ce2a26e2e9b481855473fc3b3e4e54d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/stopwatch',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/string' => array(
            'pretty_version' => 'v6.1.4',
            'version' => '6.1.4.0',
            'reference' => '290972cad7b364e3befaa74ba0ec729800fb161c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/string',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/var-exporter' => array(
            'pretty_version' => 'v6.1.3',
            'version' => '6.1.3.0',
            'reference' => 'b49350f45cebbba6e5286485264b912f2bcfc9ef',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/var-exporter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/yaml' => array(
            'pretty_version' => 'v5.4.12',
            'version' => '5.4.12.0',
            'reference' => '7a3aa21ac8ab1a96cc6de5bbcab4bc9fc943b18c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/yaml',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'theseer/tokenizer' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'reference' => '34a41e998c2183e22995f158c581e7b5e755ab9e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../theseer/tokenizer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'typo3/form' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '5.3.3',
            ),
        ),
        'typo3/imagine' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.3.0',
            ),
        ),
        'typo3/media' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.1.1',
            ),
        ),
        'typo3/neos' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.1.1',
            ),
        ),
        'typo3/neos-base-distribution' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.1.1',
            ),
        ),
        'typo3/neos-kickstarter' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.1.1',
            ),
        ),
        'typo3/neos-seo' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.3.3',
            ),
        ),
        'typo3/setup' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '5.0.0',
            ),
        ),
        'typo3/twitter-bootstrap' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.0.7',
            ),
        ),
        'typo3/typo3cr' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.1.1',
            ),
        ),
        'typo3/typoscript' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.1.1',
            ),
        ),
        'typo3fluid/fluid' => array(
            'pretty_version' => '2.7.2',
            'version' => '2.7.2.0',
            'reference' => '50ee1ee19ee00947c92bcb554bbea4fb5463b468',
            'type' => 'library',
            'install_path' => __DIR__ . '/../typo3fluid/fluid',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webexcess/redirecthandler-backend' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
    ),
);
