<?php 
declare(strict_types=1);

namespace Neos\Flow\Persistence;

/*
 * This file is part of the Neos.Flow package.
 *
 * (c) Contributors of the Neos Project - www.neos.io
 *
 * This package is Open Source Software. For the full copyright and license
 * information, please view the LICENSE file which was distributed with this
 * source code.
 */

use Neos\Flow\Annotations as Flow;

/**
 * A container for the list of allowed objects to be persisted during this request.
 *
 * @Flow\Scope("singleton")
 */
class AllowedObjectsContainer_Original extends \SplObjectStorage
{
    /**
     * @var bool
     */
    protected $checkNext = false;

    /**
     * Set the internal flag to return true for `shouldCheck()` on the next invocation.
     *
     * @param bool $checkNext
     */
    public function checkNext(bool $checkNext = true): void
    {
        $this->checkNext = $checkNext;
    }

    /**
     * Returns true if allowed objects should be checked this time and resets the internal flag to false,
     * so the next call will return false unless `checkNext(true)` is called again.
     *
     * @return bool
     */
    public function shouldCheck(): bool
    {
        $shouldCheck = $this->checkNext;
        $this->checkNext = false;
        return $shouldCheck;
    }
}

#
# Start of Flow generated Proxy code
#
/**
 * A container for the list of allowed objects to be persisted during this request.
 *
 * @Flow\Scope("singleton")
 * @codeCoverageIgnore
 */
final class AllowedObjectsContainer extends AllowedObjectsContainer_Original implements \Neos\Flow\ObjectManagement\Proxy\ProxyInterface {

    use \Neos\Flow\ObjectManagement\Proxy\ObjectSerializationTrait;


    /**
     * Autogenerated Proxy Method
     */
    public function __construct()
    {
        if (get_class($this) === 'Neos\Flow\Persistence\AllowedObjectsContainer') \Neos\Flow\Core\Bootstrap::$staticObjectManager->setInstance('Neos\Flow\Persistence\AllowedObjectsContainer', $this);
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __sleep()
    {
            $result = NULL;
        $this->Flow_Object_PropertiesToSerialize = array();
        unset($this->Flow_Persistence_RelatedEntities);

        $transientProperties = array (
);
        $propertyVarTags = array (
  'checkNext' => 'boolean',
);
        $result = $this->Flow_serializeRelatedEntities($transientProperties, $propertyVarTags);
        return $result;
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __wakeup()
    {
        if (get_class($this) === 'Neos\Flow\Persistence\AllowedObjectsContainer') \Neos\Flow\Core\Bootstrap::$staticObjectManager->setInstance('Neos\Flow\Persistence\AllowedObjectsContainer', $this);

        $this->Flow_setRelatedEntities();
    }
}
# PathAndFilename: /Applications/MAMP/htdocs/neos-example/Packages/Framework/Neos.Flow/Classes/Persistence/AllowedObjectsContainer.php
#