<?php 
namespace Neos\Flow\Security\Authentication\Token;

/*
 * This file is part of the Neos.Flow package.
 *
 * (c) Contributors of the Neos Project - www.neos.io
 *
 * This package is Open Source Software. For the full copyright and license
 * information, please view the LICENSE file which was distributed with this
 * source code.
 */

use Neos\Flow\Mvc\ActionRequest;

/**
 * An authentication token used for simple username and password authentication via HTTP Basic Auth.
 */
class UsernamePasswordHttpBasic_Original extends UsernamePassword implements SessionlessTokenInterface
{
    /**
     * Updates the username and password credentials from the HTTP authorization header.
     * Sets the authentication status to AUTHENTICATION_NEEDED, if the header has been
     * sent, to NO_CREDENTIALS_GIVEN if no authorization header was there.
     *
     * @param ActionRequest $actionRequest The current action request instance
     * @return void
     */
    public function updateCredentials(ActionRequest $actionRequest)
    {
        $this->credentials = ['username' => null, 'password' => null];
        $this->authenticationStatus = self::NO_CREDENTIALS_GIVEN;

        $authorizationHeader = $actionRequest->getHttpRequest()->getHeaderLine('Authorization');
        if (strpos($authorizationHeader, 'Basic ') !== 0) {
            return;
        }

        $credentials = base64_decode(substr($authorizationHeader, 6));
        list($username, $password) = explode(':', $credentials, 2);
        $this->credentials['username'] = $username;
        $this->credentials['password'] = $password;
        $this->authenticationStatus = self::AUTHENTICATION_NEEDED;
    }
}

#
# Start of Flow generated Proxy code
#
/**
 * An authentication token used for simple username and password authentication via HTTP Basic Auth.
 * @codeCoverageIgnore
 */
class UsernamePasswordHttpBasic extends UsernamePasswordHttpBasic_Original implements \Neos\Flow\ObjectManagement\Proxy\ProxyInterface {

    use \Neos\Flow\ObjectManagement\Proxy\ObjectSerializationTrait;


    /**
     * Autogenerated Proxy Method
     */
    public function __sleep()
    {
            $result = NULL;
        $this->Flow_Object_PropertiesToSerialize = array();
        unset($this->Flow_Persistence_RelatedEntities);

        $transientProperties = array (
  0 => 'credentials',
);
        $propertyVarTags = array (
  'credentials' => 'array',
  'authenticationProviderName' => 'string',
  'authenticationStatus' => 'integer',
  'account' => 'Neos\\Flow\\Security\\Account',
  'requestPatterns' => 'array',
  'entryPoint' => 'Neos\\Flow\\Security\\Authentication\\EntryPointInterface',
  'options' => 'array',
);
        $result = $this->Flow_serializeRelatedEntities($transientProperties, $propertyVarTags);
        return $result;
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __wakeup()
    {

        $this->Flow_setRelatedEntities();
    }
}
# PathAndFilename: /Applications/MAMP/htdocs/neos-example/Packages/Framework/Neos.Flow/Classes/Security/Authentication/Token/UsernamePasswordHttpBasic.php
#