<?php 
namespace Neos\Neos\EventLog\Domain\Model;

/*
 * This file is part of the Neos.Neos package.
 *
 * (c) Contributors of the Neos Project - www.neos.io
 *
 * This package is Open Source Software. For the full copyright and license
 * information, please view the LICENSE file which was distributed with this
 * source code.
 */

/**
 * Helper Model which groups a number of events on a given day. Used especially in the view.
 */
class EventsOnDate_Original
{
    /**
     * @var \DateTime
     */
    protected $day;

    /**
     * @var array<Event>
     */
    protected $events = [];

    /**
     * @param \DateTime $day
     */
    public function __construct(\DateTime $day)
    {
        $this->day = $day;
    }

    /**
     * add another event to this group
     *
     * @param Event $event
     */
    public function add(Event $event)
    {
        $this->events[] = $event;
    }

    /**
     * @return array
     */
    public function getEvents()
    {
        return $this->events;
    }

    /**
     * @return \DateTime
     */
    public function getDay()
    {
        return $this->day;
    }
}

#
# Start of Flow generated Proxy code
#
/**
 * Helper Model which groups a number of events on a given day. Used especially in the view.
 * @codeCoverageIgnore
 */
class EventsOnDate extends EventsOnDate_Original implements \Neos\Flow\ObjectManagement\Proxy\ProxyInterface {

    use \Neos\Flow\ObjectManagement\Proxy\ObjectSerializationTrait;


    /**
     * Autogenerated Proxy Method
     *
     * @param \DateTime $day
     */
    public function __construct()
    {
        $arguments = func_get_args();

        if (!array_key_exists(0, $arguments)) $arguments[0] = \Neos\Flow\Core\Bootstrap::$staticObjectManager->get('DateTime');
        if (!array_key_exists(0, $arguments)) throw new \Neos\Flow\ObjectManagement\Exception\UnresolvedDependenciesException('Missing required constructor argument $day in class ' . __CLASS__ . '. Note that constructor injection is only support for objects of scope singleton (and this is not a singleton) – for other scopes you must pass each required argument to the constructor yourself.', 1296143788);
        parent::__construct(...$arguments);
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __sleep()
    {
            $result = NULL;
        $this->Flow_Object_PropertiesToSerialize = array();
        unset($this->Flow_Persistence_RelatedEntities);

        $transientProperties = array (
);
        $propertyVarTags = array (
  'day' => '\\DateTime',
  'events' => 'array<Neos\\Neos\\EventLog\\Domain\\Model\\Event>',
);
        $result = $this->Flow_serializeRelatedEntities($transientProperties, $propertyVarTags);
        return $result;
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __wakeup()
    {

        $this->Flow_setRelatedEntities();
    }
}
# PathAndFilename: /Applications/MAMP/htdocs/neos-example/Packages/Application/Neos.Neos/Classes/EventLog/Domain/Model/EventsOnDate.php
#