<?php 
declare(strict_types=1);

namespace Neos\Fusion\Form\Runtime\Validation\Validator;

/*
 * This file is part of the Neos.Fusion.Form package.
 *
 * (c) Contributors of the Neos Project - www.neos.io
 *
 * This package is Open Source Software. For the full copyright and license
 * information, please view the LICENSE file which was distributed with this
 * source code.
 */

use Neos\Flow\Validation\Validator\AbstractValidator;
use Neos\Flow\ResourceManagement\PersistentResource;

/**
 * The given $value is valid if it is an \Neos\Flow\ResourceManagement\PersistentResource of the configured resolution
 * Note: a value of NULL or empty string ('') is considered valid
 */
class FileTypeValidator_Original extends AbstractValidator
{
    /**
     * @var mixed[]
     */
    protected $supportedOptions = array(
        'allowedExtensions' => array([], 'Array of allowed file extensions', 'array', false),
        'allowedMediaTypes' => array([], 'Array of allowed media types', 'array', false)
    );

    /**
     * The given $value is valid if it is an \Psr\Http\Message\UploadedFileInterface of the configured resolution
     * Note: a value of NULL or empty string ('') is considered valid
     *
     * @param PersistentResource $resource
     * @return void
     * @api
     */
    protected function isValid($resource)
    {
        if (!$resource instanceof PersistentResource) {
            $this->addError('The given value was not a PersistentResource instance.', 1616425674);
            return;
        }
        if ($this->options['allowedExtensions'] && !in_array($resource->getFileExtension(), $this->options['allowedExtensions'])) {
            $this->addError(
                'The file extension has to be one of "%s", "%s" is not allowed.',
                1616425683,
                [
                    implode(', ', $this->options['allowedExtensions']),
                    $resource->getFileExtension()
                ]
            );
        }
        if ($this->options['allowedMediaTypes'] && !in_array($resource->getMediaType(), $this->options['allowedMediaTypes'])) {
            $this->addError(
                'The media type has to be one of "%s", "%s" is not allowed.',
                1616425912,
                [
                    implode(', ', $this->options['allowedMediaTypes']),
                    $resource->getMediaType()
                ]
            );
        }
    }
}

#
# Start of Flow generated Proxy code
#
/**
 * The given $value is valid if it is an \Neos\Flow\ResourceManagement\PersistentResource of the configured resolution
 * Note: a value of NULL or empty string ('') is considered valid
 * @codeCoverageIgnore
 */
class FileTypeValidator extends FileTypeValidator_Original implements \Neos\Flow\ObjectManagement\Proxy\ProxyInterface {

    use \Neos\Flow\ObjectManagement\Proxy\ObjectSerializationTrait;


    /**
     * Autogenerated Proxy Method
     */
    public function __sleep()
    {
            $result = NULL;
        $this->Flow_Object_PropertiesToSerialize = array();
        unset($this->Flow_Persistence_RelatedEntities);

        $transientProperties = array (
);
        $propertyVarTags = array (
  'supportedOptions' => 'array<mixed>',
  'acceptsEmptyValues' => 'boolean',
  'options' => 'array',
  'resultStack' => 'array<Neos\\Error\\Messages\\Result>',
);
        $result = $this->Flow_serializeRelatedEntities($transientProperties, $propertyVarTags);
        return $result;
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __wakeup()
    {

        $this->Flow_setRelatedEntities();
    }
}
# PathAndFilename: /Applications/MAMP/htdocs/neos-example/Packages/Application/Neos.Fusion.Form/Classes/Runtime/Validation/Validator/FileTypeValidator.php
#