<?php 
namespace Neos\ContentRepository\Domain\Model\IntraDimension;

/*
 * This file is part of the Neos.ContentRepository package.
 *
 * (c) Contributors of the Neos Project - www.neos.io
 *
 * This package is Open Source Software. For the full copyright and license
 * information, please view the LICENSE file which was distributed with this
 * source code.
 */

/**
 * The content dimension value domain model
 */
class ContentDimensionValue_Original
{
    /**
     * @var string
     */
    protected $value;

    /**
     * @var ContentDimensionValue
     */
    protected $fallback;

    /**
     * @var array
     */
    protected $variants = [];

    /**
     * @var int
     */
    protected $depth = 0;

    /**
     * @param string $value
     * @param ContentDimensionValue|null $fallback
     */
    public function __construct(string $value, ContentDimensionValue $fallback = null)
    {
        $this->value = $value;
        if ($fallback) {
            $this->fallback = $fallback;
            $this->depth = $fallback->getDepth() + 1;
        }
    }

    /**
     * @param ContentDimensionValue $variant
     * @return void
     */
    public function registerVariant(ContentDimensionValue $variant)
    {
        $this->variants[$variant->getValue()] = $variant;
    }

    /**
     * @return array|ContentDimensionValue[]
     */
    public function getVariants(): array
    {
        return $this->variants;
    }

    /**
     * @return ContentDimensionValue|null
     */
    public function getFallback()
    {
        return $this->fallback;
    }

    /**
     * @return string
     */
    public function getValue(): string
    {
        return $this->value;
    }

    /**
     * @return int
     */
    public function getDepth(): int
    {
        return $this->depth;
    }

    /**
     * @param ContentDimensionValue $fallback
     * @return int
     * @throws Exception\InvalidFallbackException
     */
    public function calculateFallbackDepth(ContentDimensionValue $fallback): int
    {
        $fallbackDepth = 0;
        $fallbackFound = false;
        $currentFallback = $this;
        while ($currentFallback && !$fallbackFound) {
            if ($currentFallback === $fallback) {
                $fallbackFound = true;
            } else {
                $currentFallback = $currentFallback->getFallback();
                $fallbackDepth++;
            }
        }
        if (!$fallbackFound) {
            throw new Exception\InvalidFallbackException();
        }

        return $fallbackDepth;
    }

    /**
     * @return string
     */
    public function __toString(): string
    {
        return $this->value;
    }
}

#
# Start of Flow generated Proxy code
#
/**
 * The content dimension value domain model
 * @codeCoverageIgnore
 */
class ContentDimensionValue extends ContentDimensionValue_Original implements \Neos\Flow\ObjectManagement\Proxy\ProxyInterface {

    use \Neos\Flow\ObjectManagement\Proxy\ObjectSerializationTrait;


    /**
     * Autogenerated Proxy Method
     *
     * @param string $value
     * @param ContentDimensionValue|null $fallback
     */
    public function __construct()
    {
        $arguments = func_get_args();
        if (!array_key_exists(0, $arguments)) throw new \Neos\Flow\ObjectManagement\Exception\UnresolvedDependenciesException('Missing required constructor argument $value in class ' . __CLASS__ . '. Note that constructor injection is only support for objects of scope singleton (and this is not a singleton) – for other scopes you must pass each required argument to the constructor yourself.', 1296143788);
        parent::__construct(...$arguments);
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __sleep()
    {
            $result = NULL;
        $this->Flow_Object_PropertiesToSerialize = array();
        unset($this->Flow_Persistence_RelatedEntities);

        $transientProperties = array (
);
        $propertyVarTags = array (
  'value' => 'string',
  'fallback' => 'Neos\\ContentRepository\\Domain\\Model\\IntraDimension\\ContentDimensionValue',
  'variants' => 'array',
  'depth' => 'integer',
);
        $result = $this->Flow_serializeRelatedEntities($transientProperties, $propertyVarTags);
        return $result;
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __wakeup()
    {

        $this->Flow_setRelatedEntities();
    }
}
# PathAndFilename: /Applications/MAMP/htdocs/neos-example/Packages/Application/Neos.ContentRepository/Classes/Domain/Model/IntraDimension/ContentDimensionValue.php
#