<?php 
declare(strict_types=1);

namespace Neos\Flow\Http\Middleware;

/*
 * This file is part of the Neos.Flow package.
 *
 * (c) Contributors of the Neos Project - www.neos.io
 *
 * This package is Open Source Software. For the full copyright and license
 * information, please view the LICENSE file which was distributed with this
 * source code.
 */

use Neos\Flow\Annotations as Flow;
use Neos\Flow\Http\Cookie;
use Neos\Flow\Session\CookieEnabledInterface;
use Neos\Flow\Session\SessionManager;
use Neos\Flow\Session\SessionManagerInterface;
use Neos\Flow\Utility\Algorithms;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Server\MiddlewareInterface;
use Psr\Http\Server\RequestHandlerInterface;

/**
 * A middleware that handles the session in a HTTP request
 */
class SessionMiddleware_Original implements MiddlewareInterface
{
    /**
     * @Flow\InjectConfiguration(package="Neos.Flow", path="session")
     * @var array
     */
    protected $sessionSettings;

    /**
     * @Flow\Inject(lazy=false)
     * @var SessionManagerInterface
     */
    protected $sessionManager;

    public function process(ServerRequestInterface $request, RequestHandlerInterface $next): ResponseInterface
    {
        if (!$this->sessionManager instanceof SessionManager) {
            return $next->handle($request);
        }

        $sessionCookieName = $this->sessionSettings['name'];
        /** @var ServerRequestInterface $request */
        $cookies = $request->getCookieParams();

        if (!isset($cookies[$sessionCookieName])) {
            $sessionCookie = $this->prepareCookie($sessionCookieName, Algorithms::generateRandomString(32));
            $this->sessionManager->createCurrentSessionFromCookie($sessionCookie);
            return $this->handleSetCookie($next->handle($request));
        }

        $sessionIdentifier = $cookies[$sessionCookieName];
        $sessionCookie = $this->prepareCookie((string) $sessionCookieName, (string) $sessionIdentifier);
        $this->sessionManager->initializeCurrentSessionFromCookie($sessionCookie);
        $this->sessionManager->getCurrentSession()->resume();

        return $this->handleSetCookie($next->handle($request));
    }

    /**
     * @param ResponseInterface $response
     * @return ResponseInterface
     */
    protected function handleSetCookie(ResponseInterface $response): ResponseInterface
    {
        $currentSession = $this->sessionManager->getCurrentSession();
        if (!$currentSession->isStarted() || !($currentSession instanceof CookieEnabledInterface)) {
            return $response;
        }

        return $response->withAddedHeader('Set-Cookie', (string)$currentSession->getSessionCookie());
    }

    /**
     * Prepares a cookie object for the session.
     *
     * @param string $name
     * @param string $value
     * @return Cookie
     */
    protected function prepareCookie(string $name, string $value)
    {
        return new Cookie(
            $name,
            // @see https://github.com/neos/flow-development-collection/issues/2133
            trim(urldecode($value), '"'),
            0,
            $this->sessionSettings['cookie']['lifetime'],
            $this->sessionSettings['cookie']['domain'],
            $this->sessionSettings['cookie']['path'],
            $this->sessionSettings['cookie']['secure'],
            $this->sessionSettings['cookie']['httponly'],
            $this->sessionSettings['cookie']['samesite']
        );
    }
}

#
# Start of Flow generated Proxy code
#
/**
 * A middleware that handles the session in a HTTP request
 * @codeCoverageIgnore
 */
class SessionMiddleware extends SessionMiddleware_Original implements \Neos\Flow\ObjectManagement\Proxy\ProxyInterface {

    use \Neos\Flow\ObjectManagement\Proxy\ObjectSerializationTrait, \Neos\Flow\ObjectManagement\DependencyInjection\PropertyInjectionTrait;


    /**
     * Autogenerated Proxy Method
     */
    public function __construct()
    {
        if ('Neos\Flow\Http\Middleware\SessionMiddleware' === get_class($this)) {
            $this->Flow_Proxy_injectProperties();
        }
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __sleep()
    {
            $result = NULL;
        $this->Flow_Object_PropertiesToSerialize = array();
        unset($this->Flow_Persistence_RelatedEntities);

        $transientProperties = array (
);
        $propertyVarTags = array (
  'sessionSettings' => 'array',
  'sessionManager' => 'Neos\\Flow\\Session\\SessionManagerInterface',
);
        $result = $this->Flow_serializeRelatedEntities($transientProperties, $propertyVarTags);
        return $result;
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __wakeup()
    {

        $this->Flow_setRelatedEntities();
        $this->Flow_Proxy_injectProperties();
    }

    /**
     * Autogenerated Proxy Method
     */
    private function Flow_Proxy_injectProperties()
    {
        $this->sessionManager = \Neos\Flow\Core\Bootstrap::$staticObjectManager->get('Neos\Flow\Session\SessionManagerInterface');
        $this->sessionSettings = \Neos\Flow\Core\Bootstrap::$staticObjectManager->get(\Neos\Flow\Configuration\ConfigurationManager::class)->getConfiguration('Settings', 'Neos.Flow.session');
        $this->Flow_Injected_Properties = array (
  0 => 'sessionManager',
  1 => 'sessionSettings',
);
    }
}
# PathAndFilename: /Applications/MAMP/htdocs/neos-example/Packages/Framework/Neos.Flow/Classes/Http/Middleware/SessionMiddleware.php
#