<?php 
declare(strict_types=1);

namespace Neos\Fusion\Form\Runtime\Domain;

/*
 * This file is part of the Neos.Fusion.Form package.
 *
 * (c) Contributors of the Neos Project - www.neos.io
 *
 * This package is Open Source Software. For the full copyright and license
 * information, please view the LICENSE file which was distributed with this
 * source code.
 */

use Neos\Flow\Annotations as Flow;
use Neos\Flow\Mvc\ActionRequest;
use Neos\Flow\Security\Cryptography\HashService;

class FormRequestFactory_Original
{
    /**
     * @var HashService
     * @Flow\Inject
     */
    protected $hashService;

    /**
     * Prepare subrequest for the identifier namespace and transfer the arguments
     * only arguments present in __trustedProperties are transferred
     *
     * @param ActionRequest $parentRequest
     * @param string $identifier
     * @return ActionRequest
     */
    public function createFormRequest(ActionRequest $parentRequest, string $identifier): ActionRequest
    {
        $formRequest = $parentRequest->createSubRequest();
        $formRequest->setArgumentNamespace($identifier);
        if ($parentRequest->hasArgument($identifier) === true && is_array($parentRequest->getArgument($identifier))) {
            $submittedData = $parentRequest->getArgument($identifier);
            if ($submittedData['__trustedProperties']) {
                $trustedProperties = unserialize($this->hashService->validateAndStripHmac($submittedData['__trustedProperties']), ['allowed_classes' => false]);
                $subrequestArguments = $this->filterSubmittedDataWithTrustedProperties($submittedData, $trustedProperties);
            } else {
                $subrequestArguments = [];
            }
            $formRequest->setArguments($subrequestArguments);
        }
        return $formRequest;
    }

    /**
     * Filter incoming data with the trusted properties data-structure recursively this ensures only values that
     * where actually rendered by the form are passed as result to the form process
     *
     * @param mixed[] $submittedData
     * @param mixed[] $trustedProperties
     * @return mixed[]
     * @throws \Exception
     */
    protected function filterSubmittedDataWithTrustedProperties($submittedData, array $trustedProperties): array
    {
        $filteredData = [];
        if (!is_array($submittedData)) {
            return $filteredData;
        }
        foreach ($trustedProperties as $fieldName => $trustedProperty) {
            if (array_key_exists($fieldName, $submittedData)) {
                if ($trustedProperty === 1) {
                    $filteredData[$fieldName] = $submittedData[$fieldName];
                } elseif (is_array($trustedProperty)) {
                    $filteredData[$fieldName] = $this->filterSubmittedDataWithTrustedProperties($submittedData[$fieldName], $trustedProperty);
                } else {
                    throw new \Exception('This exception should never be thrown as trusted properties are either arrays or 1');
                }
            }
        }
        return $filteredData;
    }
}

#
# Start of Flow generated Proxy code
#

class FormRequestFactory extends FormRequestFactory_Original implements \Neos\Flow\ObjectManagement\Proxy\ProxyInterface {

    use \Neos\Flow\ObjectManagement\Proxy\ObjectSerializationTrait, \Neos\Flow\ObjectManagement\DependencyInjection\PropertyInjectionTrait;


    /**
     * Autogenerated Proxy Method
     */
    public function __construct()
    {
        if ('Neos\Fusion\Form\Runtime\Domain\FormRequestFactory' === get_class($this)) {
            $this->Flow_Proxy_injectProperties();
        }
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __sleep()
    {
            $result = NULL;
        $this->Flow_Object_PropertiesToSerialize = array();
        unset($this->Flow_Persistence_RelatedEntities);

        $transientProperties = array (
);
        $propertyVarTags = array (
  'hashService' => 'Neos\\Flow\\Security\\Cryptography\\HashService',
);
        $result = $this->Flow_serializeRelatedEntities($transientProperties, $propertyVarTags);
        return $result;
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __wakeup()
    {

        $this->Flow_setRelatedEntities();
        $this->Flow_Proxy_injectProperties();
    }

    /**
     * Autogenerated Proxy Method
     */
    private function Flow_Proxy_injectProperties()
    {
        $this->Flow_Proxy_LazyPropertyInjection('Neos\Flow\Security\Cryptography\HashService', 'Neos\Flow\Security\Cryptography\HashService', 'hashService', '62d57ff7e7ce903303c867dd468c12fd', function() { return \Neos\Flow\Core\Bootstrap::$staticObjectManager->get('Neos\Flow\Security\Cryptography\HashService'); });
        $this->Flow_Injected_Properties = array (
  0 => 'hashService',
);
    }
}
# PathAndFilename: /Applications/MAMP/htdocs/neos-example/Packages/Application/Neos.Fusion.Form/Classes/Runtime/Domain/FormRequestFactory.php
#