<?php 
namespace Neos\ContentRepository\Security\Authorization\Privilege\Node;

/*
 * This file is part of the Neos.ContentRepository package.
 *
 * (c) Contributors of the Neos Project - www.neos.io
 *
 * This package is Open Source Software. For the full copyright and license
 * information, please view the LICENSE file which was distributed with this
 * source code.
 */


/**
 * An Eel context matching expression for the node privileges including
 * node properties.
 */
class PropertyAwareNodePrivilegeContext_Original extends NodePrivilegeContext
{
    /**
     * @var array
     */
    protected $propertyNames = [];

    /**
     * @param string|array $propertyNames
     * @return boolean
     */
    public function nodePropertyIsIn($propertyNames)
    {
        if (!is_array($propertyNames)) {
            $propertyNames = [$propertyNames];
        }
        $this->propertyNames = $propertyNames;
        return true;
    }

    /**
     * @return array
     */
    public function getNodePropertyNames()
    {
        return $this->propertyNames;
    }

    /**
     * Whether or not this context is bound to specific properties
     *
     * @return boolean
     */
    public function hasProperties()
    {
        return $this->propertyNames !== [];
    }
}

#
# Start of Flow generated Proxy code
#
/**
 * An Eel context matching expression for the node privileges including
 * node properties.
 * @codeCoverageIgnore
 */
class PropertyAwareNodePrivilegeContext extends PropertyAwareNodePrivilegeContext_Original implements \Neos\Flow\ObjectManagement\Proxy\ProxyInterface {

    use \Neos\Flow\ObjectManagement\Proxy\ObjectSerializationTrait, \Neos\Flow\ObjectManagement\DependencyInjection\PropertyInjectionTrait;


    /**
     * Autogenerated Proxy Method
     *
     * @param NodeInterface $node
     */
    public function __construct()
    {
        $arguments = func_get_args();
        parent::__construct(...$arguments);
        if ('Neos\ContentRepository\Security\Authorization\Privilege\Node\PropertyAwareNodePrivilegeContext' === get_class($this)) {
            $this->Flow_Proxy_injectProperties();
        }
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __sleep()
    {
            $result = NULL;
        $this->Flow_Object_PropertiesToSerialize = array();
        unset($this->Flow_Persistence_RelatedEntities);

        $transientProperties = array (
);
        $propertyVarTags = array (
  'propertyNames' => 'array',
  'transientNodeCache' => 'Neos\\ContentRepository\\Security\\Authorization\\Privilege\\Node\\TransientNodeCache',
  'contextFactory' => 'Neos\\ContentRepository\\Domain\\Service\\ContextFactory',
  'securityContext' => 'Neos\\Flow\\Security\\Context',
  'contentDimensionPresetSource' => 'Neos\\ContentRepository\\Domain\\Service\\ContentDimensionPresetSourceInterface',
  'node' => 'Neos\\ContentRepository\\Domain\\Model\\NodeInterface',
);
        $result = $this->Flow_serializeRelatedEntities($transientProperties, $propertyVarTags);
        return $result;
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __wakeup()
    {

        $this->Flow_setRelatedEntities();
        $this->Flow_Proxy_injectProperties();
    }

    /**
     * Autogenerated Proxy Method
     */
    private function Flow_Proxy_injectProperties()
    {
        $this->Flow_Proxy_LazyPropertyInjection('Neos\ContentRepository\Security\Authorization\Privilege\Node\TransientNodeCache', 'Neos\ContentRepository\Security\Authorization\Privilege\Node\TransientNodeCache', 'transientNodeCache', '0c33486ced9e8c8927f6a4d36468ad0b', function() { return \Neos\Flow\Core\Bootstrap::$staticObjectManager->get('Neos\ContentRepository\Security\Authorization\Privilege\Node\TransientNodeCache'); });
        $this->Flow_Proxy_LazyPropertyInjection('Neos\ContentRepository\Domain\Service\ContextFactory', 'Neos\ContentRepository\Domain\Service\ContextFactory', 'contextFactory', 'fe29cc43adf119dd42e0028ba09ce06b', function() { return \Neos\Flow\Core\Bootstrap::$staticObjectManager->get('Neos\ContentRepository\Domain\Service\ContextFactory'); });
        $this->Flow_Proxy_LazyPropertyInjection('Neos\Flow\Security\Context', 'Neos\Flow\Security\Context', 'securityContext', 'f7e2ddeaebd191e228b8c2e4dc7f1f83', function() { return \Neos\Flow\Core\Bootstrap::$staticObjectManager->get('Neos\Flow\Security\Context'); });
        $this->Flow_Proxy_LazyPropertyInjection('Neos\ContentRepository\Domain\Service\ContentDimensionPresetSourceInterface', 'Neos\Neos\Domain\Service\ConfigurationContentDimensionPresetSource', 'contentDimensionPresetSource', '33404cce491062aa2636da962a6cf674', function() { return \Neos\Flow\Core\Bootstrap::$staticObjectManager->get('Neos\ContentRepository\Domain\Service\ContentDimensionPresetSourceInterface'); });
        $this->Flow_Injected_Properties = array (
  0 => 'transientNodeCache',
  1 => 'contextFactory',
  2 => 'securityContext',
  3 => 'contentDimensionPresetSource',
);
    }
}
# PathAndFilename: /Applications/MAMP/htdocs/neos-example/Packages/Application/Neos.ContentRepository/Classes/Security/Authorization/Privilege/Node/PropertyAwareNodePrivilegeContext.php
#