<?php 
declare(strict_types=1);

namespace Neos\Fusion\Core\ObjectTreeParser\ExceptionMessage;

/*
 * This file is part of the Neos.Fusion package.
 *
 * (c) Contributors of the Neos Project - www.neos.io
 *
 * This package is Open Source Software. For the full copyright and license
 * information, please view the LICENSE file which was distributed with this
 * source code.
 */

class MessageLinePart_Original
{
    public function __construct(
        protected string $linePart,
        protected bool $isEof = false
    ) {
    }

    public function line(int $offset = 0): string
    {
        return mb_substr($this->linePart, $offset);
    }

    public function linePrint(int $offset = 0): string
    {
        $line = $this->line($offset);
        if (mb_strlen($line) > 1) {
            return "'$line'";
        }
        return $this->charPrint($offset);
    }

    public function char(int $index = 0): string
    {
        if ($index < 0) {
            return mb_substr($this->linePart, $index, 1);
        }
        return mb_substr($this->linePart, $index, $index + 1);
    }

    public function charPrint(int $index = 0): string
    {
        if ($this->isEof) {
            return '<EOF>';
        }
        return self::printable($this->char($index));
    }

    protected static function printable(string $char): string
    {
        if ($char === '') {
            return '<new line>';
        }

        // https://github.com/parsica-php/parsica/blob/main/src/Internal/Ascii.php
        return match (mb_ord($char)) {
            0 => "<null>",
            9 => "<horizontal tab>",
            10 => "<line feed>",
            11 => "<vertical tab>",
            13 => "<carriage return>",
            25 => "<end of medium>",
            27 => "<escape>",
            32 => "<space>",
            34 => "<double quote>",
            39 => "<single quote>",
            47 => "<slash>",
            92 => "<backslash>",
            130 => "<single low-9 quotation mark>",
            132 => "<double low-9 quotation mark>",
            145 => "<left single quotation mark>",
            146 => "<right single quotation mark>",
            147 => "<left double quotation mark>",
            148 => "<right double quotation mark>",
            160 => "<non-breaking space>",
            default => "'$char'",
        };
    }
}

#
# Start of Flow generated Proxy code
#

class MessageLinePart extends MessageLinePart_Original implements \Neos\Flow\ObjectManagement\Proxy\ProxyInterface {

    use \Neos\Flow\ObjectManagement\Proxy\ObjectSerializationTrait;


    /**
     * Autogenerated Proxy Method
     */
    public function __construct()
    {
        $arguments = func_get_args();
        if (!array_key_exists(0, $arguments)) throw new \Neos\Flow\ObjectManagement\Exception\UnresolvedDependenciesException('Missing required constructor argument $linePart in class ' . __CLASS__ . '. Note that constructor injection is only support for objects of scope singleton (and this is not a singleton) – for other scopes you must pass each required argument to the constructor yourself.', 1296143788);
        parent::__construct(...$arguments);
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __sleep()
    {
            $result = NULL;
        $this->Flow_Object_PropertiesToSerialize = array();
        unset($this->Flow_Persistence_RelatedEntities);

        $transientProperties = array (
);
        $propertyVarTags = array (
);
        $result = $this->Flow_serializeRelatedEntities($transientProperties, $propertyVarTags);
        return $result;
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __wakeup()
    {

        $this->Flow_setRelatedEntities();
    }
}
# PathAndFilename: /Applications/MAMP/htdocs/neos-example/Packages/Application/Neos.Fusion/Classes/Core/ObjectTreeParser/ExceptionMessage/MessageLinePart.php
#