<?php 
namespace Neos\Neos\Domain\Model;

/*
 * This file is part of the Neos.Neos package.
 *
 * (c) Contributors of the Neos Project - www.neos.io
 *
 * This package is Open Source Software. For the full copyright and license
 * information, please view the LICENSE file which was distributed with this
 * source code.
 */

use Neos\Flow\I18n\EelHelper\TranslationHelper;
use Neos\ContentRepository\Domain\Model\NodeType;

/**
 * A plugin view definition
 *
 * @api
 */
class PluginViewDefinition_Original
{
    /**
     * @var NodeType
     */
    protected $pluginNodeType;

    /**
     * Name of this plugin view. Example: "SomePluginView"
     *
     * @var string
     */
    protected $name;

    /**
     * Configuration for this node type, can be an arbitrarily nested array.
     *
     * @var array
     */
    protected $configuration;

    /**
     * @param NodeType $pluginNodeType
     * @param string $name Name of the view
     * @param array $configuration the configuration for this node type which is defined in the schema
     */
    public function __construct(NodeType $pluginNodeType, $name, array $configuration)
    {
        $this->pluginNodeType = $pluginNodeType;
        $this->name = $name;
        $this->configuration = $configuration;
    }

    /**
     * @return NodeType
     */
    public function getPluginNodeType()
    {
        return $this->pluginNodeType;
    }

    /**
     * Returns the name of the plugin view
     *
     * @return string
     * @api
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Get the full configuration of the node type. Should only be used internally.
     *
     * Instead, use the get* / has* methods which exist for every configuration property.
     *
     * @return array
     */
    public function getConfiguration()
    {
        return $this->configuration;
    }

    /**
     * Get the human-readable label of this node type
     *
     * @return string
     * @api
     */
    public function getLabel()
    {
        $translationHelper = new TranslationHelper();
        return isset($this->configuration['label']) ? $translationHelper->translate($this->configuration['label']) : '';
    }

    /**
     * @return array
     */
    public function getControllerActionPairs()
    {
        return isset($this->configuration['controllerActions']) ? $this->configuration['controllerActions'] : [];
    }

    /**
     * Whether or not the current PluginView is configured to handle the specified controller/action pair
     *
     * @param $controllerObjectName
     * @param $actionName
     * @return boolean
     */
    public function matchesControllerActionPair($controllerObjectName, $actionName)
    {
        $controllerActionPairs = $this->getControllerActionPairs();
        return isset($controllerActionPairs[$controllerObjectName]) && in_array($actionName, $controllerActionPairs[$controllerObjectName]);
    }

    /**
     * Renders the unique name of this PluginView in the format <Package.Key>:<PluginNodeType>/<PluginViewName>
     *
     * @return string
     */
    public function __toString()
    {
        return $this->getPluginNodeType()->getName() . '/' . $this->getName();
    }
}

#
# Start of Flow generated Proxy code
#
/**
 * A plugin view definition
 *
 * @api
 * @codeCoverageIgnore
 */
class PluginViewDefinition extends PluginViewDefinition_Original implements \Neos\Flow\ObjectManagement\Proxy\ProxyInterface {

    use \Neos\Flow\ObjectManagement\Proxy\ObjectSerializationTrait;


    /**
     * Autogenerated Proxy Method
     *
     * @param NodeType $pluginNodeType
     * @param string $name Name of the view
     * @param array $configuration the configuration for this node type which is defined in the schema
     */
    public function __construct()
    {
        $arguments = func_get_args();

        if (!array_key_exists(0, $arguments)) $arguments[0] = \Neos\Flow\Core\Bootstrap::$staticObjectManager->get('Neos\ContentRepository\Domain\Model\NodeType');
        if (!array_key_exists(0, $arguments)) throw new \Neos\Flow\ObjectManagement\Exception\UnresolvedDependenciesException('Missing required constructor argument $pluginNodeType in class ' . __CLASS__ . '. Note that constructor injection is only support for objects of scope singleton (and this is not a singleton) – for other scopes you must pass each required argument to the constructor yourself.', 1296143788);
        if (!array_key_exists(1, $arguments)) throw new \Neos\Flow\ObjectManagement\Exception\UnresolvedDependenciesException('Missing required constructor argument $name in class ' . __CLASS__ . '. Note that constructor injection is only support for objects of scope singleton (and this is not a singleton) – for other scopes you must pass each required argument to the constructor yourself.', 1296143788);
        if (!array_key_exists(2, $arguments)) throw new \Neos\Flow\ObjectManagement\Exception\UnresolvedDependenciesException('Missing required constructor argument $configuration in class ' . __CLASS__ . '. Note that constructor injection is only support for objects of scope singleton (and this is not a singleton) – for other scopes you must pass each required argument to the constructor yourself.', 1296143788);
        parent::__construct(...$arguments);
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __sleep()
    {
            $result = NULL;
        $this->Flow_Object_PropertiesToSerialize = array();
        unset($this->Flow_Persistence_RelatedEntities);

        $transientProperties = array (
);
        $propertyVarTags = array (
  'pluginNodeType' => 'Neos\\ContentRepository\\Domain\\Model\\NodeType',
  'name' => 'string',
  'configuration' => 'array',
);
        $result = $this->Flow_serializeRelatedEntities($transientProperties, $propertyVarTags);
        return $result;
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __wakeup()
    {

        $this->Flow_setRelatedEntities();
    }
}
# PathAndFilename: /Applications/MAMP/htdocs/neos-example/Packages/Application/Neos.Neos/Classes/Domain/Model/PluginViewDefinition.php
#