<?php 
namespace Neos\Fusion\Afx\Dsl;

/*
 * This file is part of the Neos.Fusion.Afx package.
 *
 * (c) Contributors of the Neos Project - www.neos.io
 *
 * This package is Open Source Software. For the full copyright and license
 * information, please view the LICENSE file which was distributed with this
 * source code.
 */

use Neos\Flow\Annotations as Flow;
use Neos\Fusion;
use Neos\Fusion\Core\DslInterface;
use Neos\Fusion\Afx\Service\AfxService;
use Neos\Fusion\Afx\Exception\AfxException;
use Neos\Fusion\Afx\Parser\AfxParserException;

/**
 * Class Fusion AFX Dsl
 *
 * @Flow\Scope("singleton")
 */
class AfxDslImplementation_Original implements DslInterface
{

    /**
     * Transpile the given dsl-code to fusion-code
     *
     * @param string $code
     * @return string
     * @throws Fusion\Exception
     */
    public function transpile($code)
    {
        try {
            return AfxService::convertAfxToFusion($code);
        } catch (AfxException $afxException) {
            throw new Fusion\Exception(sprintf('Error during AFX-transpilation: %s', $afxException->getMessage()));
        } catch (AfxParserException $afxException) {
            throw new Fusion\Exception(sprintf('Error during AFX-parsing: %s', $afxException->getMessage()));
        }
    }
}

#
# Start of Flow generated Proxy code
#
/**
 * Class Fusion AFX Dsl
 *
 * @Flow\Scope("singleton")
 * @codeCoverageIgnore
 */
class AfxDslImplementation extends AfxDslImplementation_Original implements \Neos\Flow\ObjectManagement\Proxy\ProxyInterface {

    use \Neos\Flow\ObjectManagement\Proxy\ObjectSerializationTrait;


    /**
     * Autogenerated Proxy Method
     */
    public function __construct()
    {
        if (get_class($this) === 'Neos\Fusion\Afx\Dsl\AfxDslImplementation') \Neos\Flow\Core\Bootstrap::$staticObjectManager->setInstance('Neos\Fusion\Afx\Dsl\AfxDslImplementation', $this);
        if (get_class($this) === 'Neos\Fusion\Afx\Dsl\AfxDslImplementation') \Neos\Flow\Core\Bootstrap::$staticObjectManager->setInstance('Neos\Fusion\Core\DslInterface', $this);
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __sleep()
    {
            $result = NULL;
        $this->Flow_Object_PropertiesToSerialize = array();
        unset($this->Flow_Persistence_RelatedEntities);

        $transientProperties = array (
);
        $propertyVarTags = array (
);
        $result = $this->Flow_serializeRelatedEntities($transientProperties, $propertyVarTags);
        return $result;
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __wakeup()
    {
        if (get_class($this) === 'Neos\Fusion\Afx\Dsl\AfxDslImplementation') \Neos\Flow\Core\Bootstrap::$staticObjectManager->setInstance('Neos\Fusion\Afx\Dsl\AfxDslImplementation', $this);
        if (get_class($this) === 'Neos\Fusion\Afx\Dsl\AfxDslImplementation') \Neos\Flow\Core\Bootstrap::$staticObjectManager->setInstance('Neos\Fusion\Core\DslInterface', $this);

        $this->Flow_setRelatedEntities();
    }
}
# PathAndFilename: /Applications/MAMP/htdocs/neos-example/Packages/Application/Neos.Fusion.Afx/Classes/Dsl/AfxDslImplementation.php
#