<?php 
namespace Neos\Flow\Http;

use GuzzleHttp\Psr7\Uri;
use Neos\Flow\Annotations as Flow;
use Neos\Flow\Core\Bootstrap;
use Neos\Flow\Http\Helper\RequestInformationHelper;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Message\UriInterface;

/**
 * Supports to get a baseUri from various possible sources.
 *
 * @Flow\Scope("singleton")
 */
class BaseUriProvider_Original
{
    /**
     * THe possibly configured Flow base URI.
     *
     * @Flow\InjectConfiguration(package="Neos.Flow", path="http.baseUri")
     * @var string|null
     */
    protected $configuredBaseUri;

    /**
     * @Flow\Inject
     * @var Bootstrap
     */
    protected $bootstrap;

    /**
     * Get the configured framework base URI.
     *
     * @return Uri|null
     */
    private function getConfiguredBaseUri(): ?UriInterface
    {
        if ($this->configuredBaseUri === null) {
            return null;
        }

        return new Uri($this->configuredBaseUri);
    }

    /**
     * Generates a base URI from the currently active HTTP request.
     * Note that we cannot actually know the base URI if your installation
     * is in a sub directory, so in that case this will probably result in
     * a faulty base URI.
     *
     * @return UriInterface|null
     */
    private function generateBaseUriFromHttpRequest(): ?UriInterface
    {
        $activeRequestHandler = $this->bootstrap->getActiveRequestHandler();
        if (!$activeRequestHandler instanceof HttpRequestHandlerInterface) {
            return null;
        }

        $request = $activeRequestHandler->getHttpRequest();
        return RequestInformationHelper::generateBaseUri($request);
    }

    /**
     * Gives the best possible base URI with the following priority:
     * - configured base URI
     * - generated base URI from currently active server request
     * - generated base URI from specified $fallbackRequest
     *
     * To ensure a base URI can always be provided this will throw an
     * exception if none of the options yields a result.
     *
     * @param ServerRequestInterface|null $fallbackRequest HTTP request to be used if no base Uri is configured and the currently active request can't be determined (e.g. in CLI context)
     * @return UriInterface
     * @throws Exception
     */
    public function getConfiguredBaseUriOrFallbackToCurrentRequest(ServerRequestInterface $fallbackRequest = null): UriInterface
    {
        $baseUri = $this->getConfiguredBaseUri();
        if ($baseUri instanceof UriInterface) {
            return $baseUri;
        }

        $baseUri = $this->generateBaseUriFromHttpRequest();
        if ($baseUri instanceof UriInterface) {
            return $baseUri;
        }

        if ($fallbackRequest !== null) {
            return RequestInformationHelper::generateBaseUri($fallbackRequest);
        }

        throw new Exception('No base URI could be provided. This probably means a call was made outside of an HTTP request and a base URI was neither configured nor specified as $fallbackRequest.', 1567529953);
    }
}

#
# Start of Flow generated Proxy code
#
/**
 * Supports to get a baseUri from various possible sources.
 *
 * @Flow\Scope("singleton")
 * @codeCoverageIgnore
 */
class BaseUriProvider extends BaseUriProvider_Original implements \Neos\Flow\ObjectManagement\Proxy\ProxyInterface {

    use \Neos\Flow\ObjectManagement\Proxy\ObjectSerializationTrait, \Neos\Flow\ObjectManagement\DependencyInjection\PropertyInjectionTrait;


    /**
     * Autogenerated Proxy Method
     */
    public function __construct()
    {
        if (get_class($this) === 'Neos\Flow\Http\BaseUriProvider') \Neos\Flow\Core\Bootstrap::$staticObjectManager->setInstance('Neos\Flow\Http\BaseUriProvider', $this);
        if ('Neos\Flow\Http\BaseUriProvider' === get_class($this)) {
            $this->Flow_Proxy_injectProperties();
        }
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __sleep()
    {
            $result = NULL;
        $this->Flow_Object_PropertiesToSerialize = array();
        unset($this->Flow_Persistence_RelatedEntities);

        $transientProperties = array (
);
        $propertyVarTags = array (
  'configuredBaseUri' => 'string|null',
  'bootstrap' => 'Neos\\Flow\\Core\\Bootstrap',
);
        $result = $this->Flow_serializeRelatedEntities($transientProperties, $propertyVarTags);
        return $result;
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __wakeup()
    {
        if (get_class($this) === 'Neos\Flow\Http\BaseUriProvider') \Neos\Flow\Core\Bootstrap::$staticObjectManager->setInstance('Neos\Flow\Http\BaseUriProvider', $this);

        $this->Flow_setRelatedEntities();
        $this->Flow_Proxy_injectProperties();
    }

    /**
     * Autogenerated Proxy Method
     */
    private function Flow_Proxy_injectProperties()
    {
        $this->Flow_Proxy_LazyPropertyInjection('Neos\Flow\Core\Bootstrap', 'Neos\Flow\Core\Bootstrap', 'bootstrap', 'aed14e789673142988a77dfdf496f415', function() { return \Neos\Flow\Core\Bootstrap::$staticObjectManager->get('Neos\Flow\Core\Bootstrap'); });
        $this->configuredBaseUri = \Neos\Flow\Core\Bootstrap::$staticObjectManager->get(\Neos\Flow\Configuration\ConfigurationManager::class)->getConfiguration('Settings', 'Neos.Flow.http.baseUri');
        $this->Flow_Injected_Properties = array (
  0 => 'bootstrap',
  1 => 'configuredBaseUri',
);
    }
}
# PathAndFilename: /Applications/MAMP/htdocs/neos-example/Packages/Framework/Neos.Flow/Classes/Http/BaseUriProvider.php
#