<?php 
namespace Neos\Behat\Command;

/*
 * This file is part of the Neos.Behat package.
 *
 * (c) Contributors of the Neos Project - www.neos.io
 *
 * This package is Open Source Software. For the full copyright and license
 * information, please view the LICENSE file which was distributed with this
 * source code.
 */

use Neos\Flow\Annotations as Flow;
use Neos\Flow\Cli\CommandController;
use Neos\Flow\Package\Exception\UnknownPackageException;
use Neos\Flow\Package\PackageManager;
use Neos\Utility\Exception\FilesException;
use Neos\Utility\Files;

/**
 * @Flow\Scope("singleton")
 */
class BehatCommandController_Original extends CommandController
{
    /**
     * @Flow\Inject
     * @var PackageManager
     */
    protected $packageManager;

    /**
     * This command will help you to install Behat
     *
     * It will check for all necessary things to run Behat tests.
     *
     * @return void
     * @throws FilesException
     */
    public function setupCommand(): void
    {
        $behatBuildPath = FLOW_PATH_ROOT . 'Build/Behat/';
        if (is_dir($behatBuildPath)) {
            Files::emptyDirectoryRecursively($behatBuildPath);
        }
        $this->outputLine('Copying Behat setup to %s', [$behatBuildPath]);
        Files::copyDirectoryRecursively('resource://Neos.Behat/Private/Build/Behat', $behatBuildPath);

        $behatBinaryPath = FLOW_PATH_ROOT . 'bin/behat';
        if (is_file($behatBinaryPath)) {
            $this->outputLine('Removing existing Behat binary %s', [$behatBinaryPath]);
            unlink($behatBinaryPath);
        }
        $this->outputLine('Installing Behat in %s', [$behatBuildPath]);
        exec('cd "' . $behatBuildPath . '" && composer install');
        $this->outputLine();
        $this->outputLine('Installed Behat to %s, binary to %s', [$behatBuildPath, $behatBinaryPath]);

        $seleniumBinaryPath = FLOW_PATH_ROOT . 'bin/selenium-server.jar';
        if (!is_file($seleniumBinaryPath)) {
            $seleniumVersion = 'selenium-server-standalone-2.53.1.jar';
            $seleniumUrl = 'https://selenium-release.storage.googleapis.com/2.53/' . $seleniumVersion;
            $this->outputLine('Downloading Selenium %s to bin/selenium-server.jar...', [$seleniumVersion]);
            if (copy($seleniumUrl, FLOW_PATH_ROOT . 'bin/selenium-server.jar') !== true) {
                throw new \RuntimeException('Could not download selenium from ' . $seleniumUrl . '.');
            }
            $this->outputLine('Downloaded Selenium to bin/selenium-server.jar');
            $this->outputLine('You can execute it through: "java -jar selenium-server.jar"');
        } else {
            $this->outputLine('Skipped downloaded of Selenium, to update or reinstall delete bin/selenium-server.jar and run setup again');
        }
    }

    /**
     * This command will help you to kickstart Behat testing for a package
     *
     * It will add a folder Tests/Behavior in your package with a default Behat setup.
     *
     * @param string $packageName The package key
     * @param string $host The base URL for the Flow application (e.g. http://example.local/)
     * @return void
     * @throws FilesException
     * @throws UnknownPackageException
     */
    public function kickstartCommand(string $packageName, string $host): void
    {
        $this->setupCommand();

        if ($this->packageManager->isPackageAvailable($packageName)) {
            $package = $this->packageManager->getPackage($packageName);

            $behaviorTestsPath = $package->getPackagePath() . 'Tests/Behavior';
            if (!is_dir($behaviorTestsPath)) {
                Files::copyDirectoryRecursively('resource://Neos.Behat/Private/Tests/Behavior', $behaviorTestsPath);
            }

            $behatConfiguration = file_get_contents($behaviorTestsPath . '/behat.yml.dist');
            $behatConfiguration = str_replace('base_url: http://localhost/', 'base_url: ' . $host, $behatConfiguration);
            file_put_contents($behaviorTestsPath . '/behat.yml', $behatConfiguration);
        }
        $this->outputLine('Behat is installed and can be used by running: "bin/behat -c Packages/Application/%s/Tests/Behavior/behat.yml"', [$packageName]);
    }
}

#
# Start of Flow generated Proxy code
#
/**
 * @Flow\Scope("singleton")
 * @codeCoverageIgnore
 */
class BehatCommandController extends BehatCommandController_Original implements \Neos\Flow\ObjectManagement\Proxy\ProxyInterface {

    use \Neos\Flow\ObjectManagement\Proxy\ObjectSerializationTrait, \Neos\Flow\ObjectManagement\DependencyInjection\PropertyInjectionTrait;


    /**
     * Autogenerated Proxy Method
     *
     * Constructs the command controller
     */
    public function __construct()
    {
        if (get_class($this) === 'Neos\Behat\Command\BehatCommandController') \Neos\Flow\Core\Bootstrap::$staticObjectManager->setInstance('Neos\Behat\Command\BehatCommandController', $this);
        parent::__construct();
        if ('Neos\Behat\Command\BehatCommandController' === get_class($this)) {
            $this->Flow_Proxy_injectProperties();
        }
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __sleep()
    {
            $result = NULL;
        $this->Flow_Object_PropertiesToSerialize = array();
        unset($this->Flow_Persistence_RelatedEntities);

        $transientProperties = array (
);
        $propertyVarTags = array (
  'packageManager' => 'Neos\\Flow\\Package\\PackageManager',
  'request' => 'Neos\\Flow\\Cli\\Request',
  'response' => 'Neos\\Flow\\Cli\\Response',
  'arguments' => 'Neos\\Flow\\Mvc\\Controller\\Arguments',
  'commandMethodName' => 'string',
  'objectManager' => 'Neos\\Flow\\ObjectManagement\\ObjectManagerInterface',
  'commandManager' => 'Neos\\Flow\\Cli\\CommandManager',
  'output' => 'Neos\\Flow\\Cli\\ConsoleOutput',
);
        $result = $this->Flow_serializeRelatedEntities($transientProperties, $propertyVarTags);
        return $result;
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __wakeup()
    {
        if (get_class($this) === 'Neos\Behat\Command\BehatCommandController') \Neos\Flow\Core\Bootstrap::$staticObjectManager->setInstance('Neos\Behat\Command\BehatCommandController', $this);

        $this->Flow_setRelatedEntities();
        $this->Flow_Proxy_injectProperties();
    }

    /**
     * Autogenerated Proxy Method
     */
    private function Flow_Proxy_injectProperties()
    {
        $this->injectCommandManager(\Neos\Flow\Core\Bootstrap::$staticObjectManager->get('Neos\Flow\Cli\CommandManager'));
        $this->injectObjectManager(\Neos\Flow\Core\Bootstrap::$staticObjectManager->get('Neos\Flow\ObjectManagement\ObjectManagerInterface'));
        $this->Flow_Proxy_LazyPropertyInjection('Neos\Flow\Package\PackageManager', 'Neos\Flow\Package\PackageManager', 'packageManager', '5969f0154592264b520c05738a0c9f97', function() { return \Neos\Flow\Core\Bootstrap::$staticObjectManager->get('Neos\Flow\Package\PackageManager'); });
        $this->Flow_Injected_Properties = array (
  0 => 'commandManager',
  1 => 'objectManager',
  2 => 'packageManager',
);
    }
}
# PathAndFilename: /Applications/MAMP/htdocs/neos-example/Packages/Application/Neos.Behat/Classes/Command/BehatCommandController.php
#