<?php 
declare(strict_types=1);

namespace Neos\Flow\Http\Middleware;

use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Server\MiddlewareInterface;
use Psr\Http\Server\RequestHandlerInterface;

/**
 * Allows to override the request HTTP Method via different overrides in this order:
 * - a "__method" argument passes in via request body
 * - X-Http-Method-Override header
 * - X-Http-Method header
 */
class MethodOverrideMiddleware_Original implements MiddlewareInterface
{
    /**
     * Process an incoming server request and overwrite the request method of a POST based on a __method argument or either
     * the X-Http-Method-Override or X-Http-Method header.
     * @noinspection CallableParameterUseCaseInTypeContextInspection
     */
    public function process(ServerRequestInterface $request, RequestHandlerInterface $next): ResponseInterface
    {
        if ($request->getMethod() === 'POST') {
            $parsedBody = $request->getParsedBody();
            if (isset($parsedBody['__method'])) {
                $request = $request->withMethod($parsedBody['__method']);
            } elseif ($request->hasHeader('X-Http-Method-Override')) {
                $request = $request->withMethod($request->getHeaderLine('X-Http-Method-Override'));
            } elseif ($request->hasHeader('X-Http-Method')) {
                $request = $request->withMethod($request->getHeaderLine('X-Http-Method'));
            }
        }
        return $next->handle($request);
    }
}

#
# Start of Flow generated Proxy code
#
/**
 * Allows to override the request HTTP Method via different overrides in this order:
 * - a "__method" argument passes in via request body
 * - X-Http-Method-Override header
 * - X-Http-Method header
 * @codeCoverageIgnore
 */
class MethodOverrideMiddleware extends MethodOverrideMiddleware_Original implements \Neos\Flow\ObjectManagement\Proxy\ProxyInterface {

    use \Neos\Flow\ObjectManagement\Proxy\ObjectSerializationTrait;


    /**
     * Autogenerated Proxy Method
     */
    public function __sleep()
    {
            $result = NULL;
        $this->Flow_Object_PropertiesToSerialize = array();
        unset($this->Flow_Persistence_RelatedEntities);

        $transientProperties = array (
);
        $propertyVarTags = array (
);
        $result = $this->Flow_serializeRelatedEntities($transientProperties, $propertyVarTags);
        return $result;
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __wakeup()
    {

        $this->Flow_setRelatedEntities();
    }
}
# PathAndFilename: /Applications/MAMP/htdocs/neos-example/Packages/Framework/Neos.Flow/Classes/Http/Middleware/MethodOverrideMiddleware.php
#