<?php 
namespace Neos\ContentRepository\Domain\Model\InterDimension;

/*
 * This file is part of the Neos.ContentRepository package.
 *
 * (c) Contributors of the Neos Project - www.neos.io
 *
 * This package is Open Source Software. For the full copyright and license
 * information, please view the LICENSE file which was distributed with this
 * source code.
 */

use Neos\ContentRepository\Domain\Model\IntraDimension;
use Neos\ContentRepository\Domain\Utility\SubgraphUtility;

/**
 * The content subgraph domain model
 */
class ContentSubgraph_Original
{
    /**
     * @var array|IntraDimension\ContentDimensionValue[]
     */
    protected $dimensionValues = [];

    /**
     * @var string
     */
    protected $identityHash;

    /**
     * @var array
     */
    protected $fallbackEdges = [];

    /**
     * @var array
     */
    protected $variantEdges = [];

    /**
     * @var array
     */
    protected $weight = [];


    /**
     * @param array|IntraDimension\ContentDimensionValue[] $dimensionValues
     */
    public function __construct(array $dimensionValues)
    {
        $identityComponents = [];
        foreach ($dimensionValues as $dimensionName => $dimensionValue) {
            $this->dimensionValues[$dimensionName] = $dimensionValue;
            $identityComponents[$dimensionName] = $dimensionValue->getValue();
            $this->weight[$dimensionName] = $dimensionValue->getDepth();
        }
        $this->identityHash = SubgraphUtility::hashIdentityComponents($identityComponents);
    }


    /**
     * @return array|IntraDimension\ContentDimensionValue[]
     */
    public function getDimensionValues(): array
    {
        return $this->dimensionValues;
    }

    /**
     * @param string $dimensionName
     * @return IntraDimension\ContentDimensionValue
     */
    public function getDimensionValue($dimensionName): IntraDimension\ContentDimensionValue
    {
        return $this->dimensionValues[$dimensionName];
    }

    /**
     * @return string
     */
    public function getIdentityHash(): string
    {
        return $this->identityHash;
    }

    /**
     * @return array
     */
    public function getWeight(): array
    {
        return $this->weight;
    }

    /**
     * @param VariationEdge $variant
     * @return void
     */
    public function registerVariantEdge(VariationEdge $variant)
    {
        $this->variantEdges[$variant->getVariant()->getIdentityHash()] = $variant;
    }

    /**
     * @return array|VariationEdge[]
     */
    public function getVariantEdges(): array
    {
        return $this->variantEdges;
    }

    /**
     * @param VariationEdge $fallback
     * @return void
     */
    public function registerFallbackEdge(VariationEdge $fallback)
    {
        $this->fallbackEdges[$fallback->getFallback()->getIdentityHash()] = $fallback;
    }

    /**
     * @return array|VariationEdge[]
     */
    public function getFallbackEdges(): array
    {
        return $this->fallbackEdges;
    }

    /**
     * @return array|ContentSubgraph[]
     */
    public function getVariants(): array
    {
        $variants = [];
        foreach ($this->getVariantEdges() as $variantEdge) {
            $variants[$variantEdge->getVariant()->getIdentityHash()] = $variantEdge->getVariant();
        }

        return $variants;
    }

    /**
     * @return array|ContentSubgraph[]
     */
    public function getFallback(): array
    {
        $fallback = [];
        foreach ($this->getFallbackEdges() as $fallbackEdge) {
            $fallback[$fallbackEdge->getFallback()->getIdentityHash()] = $fallbackEdge->getFallback();
        }

        return $fallback;
    }
}

#
# Start of Flow generated Proxy code
#
/**
 * The content subgraph domain model
 * @codeCoverageIgnore
 */
class ContentSubgraph extends ContentSubgraph_Original implements \Neos\Flow\ObjectManagement\Proxy\ProxyInterface {

    use \Neos\Flow\ObjectManagement\Proxy\ObjectSerializationTrait;


    /**
     * Autogenerated Proxy Method
     *
     * @param array|IntraDimension\ContentDimensionValue[] $dimensionValues
     */
    public function __construct()
    {
        $arguments = func_get_args();
        if (!array_key_exists(0, $arguments)) throw new \Neos\Flow\ObjectManagement\Exception\UnresolvedDependenciesException('Missing required constructor argument $dimensionValues in class ' . __CLASS__ . '. Note that constructor injection is only support for objects of scope singleton (and this is not a singleton) – for other scopes you must pass each required argument to the constructor yourself.', 1296143788);
        parent::__construct(...$arguments);
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __sleep()
    {
            $result = NULL;
        $this->Flow_Object_PropertiesToSerialize = array();
        unset($this->Flow_Persistence_RelatedEntities);

        $transientProperties = array (
);
        $propertyVarTags = array (
  'dimensionValues' => 'array<array|IntraDimension\\ContentDimensionValue>',
  'identityHash' => 'string',
  'fallbackEdges' => 'array',
  'variantEdges' => 'array',
  'weight' => 'array',
);
        $result = $this->Flow_serializeRelatedEntities($transientProperties, $propertyVarTags);
        return $result;
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __wakeup()
    {

        $this->Flow_setRelatedEntities();
    }
}
# PathAndFilename: /Applications/MAMP/htdocs/neos-example/Packages/Application/Neos.ContentRepository/Classes/Domain/Model/InterDimension/ContentSubgraph.php
#