<?php 
namespace Neos\Neos\Ui\Domain\Dto;

/*
 * This file is part of the Neos.Neos.Ui package.
 *
 * (c) Contributors of the Neos Project - www.neos.io
 *
 * This package is Open Source Software. For the full copyright and license
 * information, please view the LICENSE file which was distributed with this
 * source code.
 */

use Neos\ContentRepository\Domain\Model\NodeInterface;
use Neos\ContentRepository\Domain\Model\NodeType;

class LoadTreeDto_Original
{
    /**
     * The currently active node in the tree
     *
     * @var NodeInterface
     */
    protected $active;

    /**
     * An (optional) node type filter
     *
     * @var NodeType|null
     */
    protected $nodeTypeFilter = null;

    /**
     * An (optional) search term filter
     *
     * @var string
     */
    protected $searchTermFilter = '';

    /**
     * Determines how many levels of the tree should be loaded
     *
     * @var integer
     */
    protected $depth = 1;

    /**
     * Get the root node
     *
     * @return NodeInterface
     */
    public function getRoot()
    {
        return $this->active->geContext()->getCurrentSiteNode();
    }

    /**
     * Set the active node
     *
     * @param NodeInterface $active
     * @return void
     */
    public function setActive(NodeInterface $active)
    {
        $this->active = $active;
    }

    /**
     * Get the active node
     *
     * @return NodeInterface
     */
    public function getActive()
    {
        return $this->active;
    }

    /**
     * Set the node type filter
     *
     * @param NodeType $nodeTypeFilter
     * @return void
     */
    public function setNodeTypeFilter(NodeType $nodeTypeFilter)
    {
        $this->nodeTypeFilter = $nodeTypeFilter;
    }

    /**
     * Get the node type filter
     *
     * @return NodeType|null
     */
    public function getNodeTypeFilter()
    {
        return $this->nodeTypeFilter;
    }

    /**
     * Set the search term filter
     *
     * @param string $searchTermFilter
     * @return void
     */
    public function setSearchTermFilter($searchTermFilter)
    {
        $this->searchTermFilter = $searchTermFilter;
    }

    /**
     * Get the search term filter
     *
     * @return string
     */
    public function getSearchTermFilter()
    {
        return $this->searchTermFilter;
    }

    /**
     * Set the depth
     *
     * @param integer $depth
     */
    public function setDepth($depth)
    {
        $this->depth = $depth;
    }

    /**
     * Get the depth
     *
     * @return integer
     */
    public function getDepth()
    {
        return $this->depth;
    }
}

#
# Start of Flow generated Proxy code
#

class LoadTreeDto extends LoadTreeDto_Original implements \Neos\Flow\ObjectManagement\Proxy\ProxyInterface {

    use \Neos\Flow\ObjectManagement\Proxy\ObjectSerializationTrait;


    /**
     * Autogenerated Proxy Method
     */
    public function __sleep()
    {
            $result = NULL;
        $this->Flow_Object_PropertiesToSerialize = array();
        unset($this->Flow_Persistence_RelatedEntities);

        $transientProperties = array (
);
        $propertyVarTags = array (
  'active' => 'Neos\\ContentRepository\\Domain\\Model\\NodeInterface',
  'nodeTypeFilter' => 'Neos\\ContentRepository\\Domain\\Model\\NodeType|null',
  'searchTermFilter' => 'string',
  'depth' => 'integer',
);
        $result = $this->Flow_serializeRelatedEntities($transientProperties, $propertyVarTags);
        return $result;
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __wakeup()
    {

        $this->Flow_setRelatedEntities();
    }
}
# PathAndFilename: /Applications/MAMP/htdocs/neos-example/Packages/Application/Neos.Neos.Ui/Classes/Domain/Dto/LoadTreeDto.php
#