<?php 
declare(strict_types=1);

namespace Neos\Flow\Configuration\Loader;

/*
 * This file is part of the Neos.Flow package.
 *
 * (c) Contributors of the Neos Project - www.neos.io
 *
 * This package is Open Source Software. For the full copyright and license
 * information, please view the LICENSE file which was distributed with this
 * source code.
 */

use Neos\Flow\Configuration\ConfigurationManager;
use Neos\Flow\Configuration\Source\YamlSource;
use Neos\Flow\Core\ApplicationContext;
use Neos\Utility\Arrays;

class SettingsLoader_Original implements LoaderInterface
{

    /**
     * @var YamlSource
     */
    private $yamlSource;

    public function __construct(YamlSource $yamlSource)
    {
        $this->yamlSource = $yamlSource;
    }

    public function load(array $packages, ApplicationContext $context): array
    {
        // Make sure that the Flow package is the first item of the packages array:
        if (isset($packages['Neos.Flow'])) {
            $flowPackage = $packages['Neos.Flow'];
            unset($packages['Neos.Flow']);
            $packages = array_merge(['Neos.Flow' => $flowPackage], $packages);
            unset($flowPackage);
        }

        $settings = [];
        foreach ($packages as $packageKey => $package) {
            if (Arrays::getValueByPath($settings, $packageKey) === null) {
                $settings = Arrays::setValueByPath($settings, $packageKey, []);
            }
            $settings = Arrays::arrayMergeRecursiveOverrule($settings, $this->yamlSource->load($package->getConfigurationPath() . ConfigurationManager::CONFIGURATION_TYPE_SETTINGS, true));
        }
        $settings = Arrays::arrayMergeRecursiveOverrule($settings, $this->yamlSource->load(FLOW_PATH_CONFIGURATION . ConfigurationManager::CONFIGURATION_TYPE_SETTINGS, true));

        foreach ($context->getHierarchy() as $contextName) {
            foreach ($packages as $package) {
                $settings = Arrays::arrayMergeRecursiveOverrule($settings, $this->yamlSource->load($package->getConfigurationPath() . $contextName . '/' . ConfigurationManager::CONFIGURATION_TYPE_SETTINGS, true));
            }
            $settings = Arrays::arrayMergeRecursiveOverrule($settings, $this->yamlSource->load(FLOW_PATH_CONFIGURATION . $contextName . '/' . ConfigurationManager::CONFIGURATION_TYPE_SETTINGS, true));
        }
        $settings['Neos']['Flow']['core']['context'] = (string)$context;
        return $settings;
    }
}

#
# Start of Flow generated Proxy code
#

class SettingsLoader extends SettingsLoader_Original implements \Neos\Flow\ObjectManagement\Proxy\ProxyInterface {

    use \Neos\Flow\ObjectManagement\Proxy\ObjectSerializationTrait;


    /**
     * Autogenerated Proxy Method
     */
    public function __construct()
    {
        $arguments = func_get_args();

        if (!array_key_exists(0, $arguments)) $arguments[0] = \Neos\Flow\Core\Bootstrap::$staticObjectManager->get('Neos\Flow\Configuration\Source\YamlSource');
        if (!array_key_exists(0, $arguments)) throw new \Neos\Flow\ObjectManagement\Exception\UnresolvedDependenciesException('Missing required constructor argument $yamlSource in class ' . __CLASS__ . '. Note that constructor injection is only support for objects of scope singleton (and this is not a singleton) – for other scopes you must pass each required argument to the constructor yourself.', 1296143788);
        parent::__construct(...$arguments);
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __sleep()
    {
            $result = NULL;
        $this->Flow_Object_PropertiesToSerialize = array();
        unset($this->Flow_Persistence_RelatedEntities);

        $transientProperties = array (
);
        $propertyVarTags = array (
  'yamlSource' => 'Neos\\Flow\\Configuration\\Source\\YamlSource',
);
        $result = $this->Flow_serializeRelatedEntities($transientProperties, $propertyVarTags);
        return $result;
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __wakeup()
    {

        $this->Flow_setRelatedEntities();
    }
}
# PathAndFilename: /Applications/MAMP/htdocs/neos-example/Packages/Framework/Neos.Flow/Classes/Configuration/Loader/SettingsLoader.php
#