<?php 

namespace TYPO3Fluid\Fluid\Core\Parser\TemplateProcessor;

/*
 * This file belongs to the package "TYPO3 Fluid".
 * See LICENSE.txt that was shipped with this package.
 */

use TYPO3Fluid\Fluid\Core\Parser\PassthroughSourceException;
use TYPO3Fluid\Fluid\Core\Parser\TemplateProcessorInterface;
use TYPO3Fluid\Fluid\Core\Rendering\RenderingContextInterface;

/**
 * This template processor has a single purpose:
 *
 * When a template file contains the string `{parsing off}`, the processor
 * throws an Exception instructing the parser to display the source instead
 * of attempting to parse the template source.
 *
 * Doing so completely disables the parser and template splitting since it
 * happens before the parser receives the source.
 */
class PassthroughSourceModifierTemplateProcessor_Original implements TemplateProcessorInterface
{
    /**
     * @param string $templateSource
     * @return string
     * @throws PassthroughSourceException
     */
    public function preProcessSource($templateSource)
    {
        if (strpos($templateSource, '{parsing off}') !== false) {
            $templateSource = str_replace('{parsing off}', '', $templateSource);
            $stopException = new PassthroughSourceException();
            $stopException->setSource($templateSource);
            throw $stopException;
        }
        return str_replace('{parsing on}', '', $templateSource);
    }

    /**
     * @param RenderingContextInterface $renderingContext
     */
    public function setRenderingContext(RenderingContextInterface $renderingContext)
    {
        // void
    }
}

#
# Start of Flow generated Proxy code
#
/**
 * This template processor has a single purpose:
 *
 * When a template file contains the string `{parsing off}`, the processor
 * throws an Exception instructing the parser to display the source instead
 * of attempting to parse the template source.
 *
 * Doing so completely disables the parser and template splitting since it
 * happens before the parser receives the source.
 * @codeCoverageIgnore
 */
class PassthroughSourceModifierTemplateProcessor extends PassthroughSourceModifierTemplateProcessor_Original implements \Neos\Flow\ObjectManagement\Proxy\ProxyInterface {

    use \Neos\Flow\ObjectManagement\Proxy\ObjectSerializationTrait;


    /**
     * Autogenerated Proxy Method
     */
    public function __sleep()
    {
            $result = NULL;
        $this->Flow_Object_PropertiesToSerialize = array();
        unset($this->Flow_Persistence_RelatedEntities);

        $transientProperties = array (
);
        $propertyVarTags = array (
);
        $result = $this->Flow_serializeRelatedEntities($transientProperties, $propertyVarTags);
        return $result;
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __wakeup()
    {

        $this->Flow_setRelatedEntities();
    }
}
# PathAndFilename: /Applications/MAMP/htdocs/neos-example/Packages/Libraries/typo3fluid/fluid/src/Core/Parser/TemplateProcessor/PassthroughSourceModifierTemplateProcessor.php
#