<?php 

namespace TYPO3Fluid\Fluid\Core\Compiler;

/*
 * This file belongs to the package "TYPO3 Fluid".
 * See LICENSE.txt that was shipped with this package.
 */

use TYPO3Fluid\Fluid\Core\Parser\ParsedTemplateInterface;
use TYPO3Fluid\Fluid\Core\Parser\ParsingState;

/**
 * Class FailedCompilingState
 *
 * Replacement ParsingState used when a template fails to compile.
 * Includes additional reasons why compiling failed.
 */
class FailedCompilingState_Original extends ParsingState implements ParsedTemplateInterface
{

    /**
     * @var string
     */
    protected $failureReason;

    /**
     * @var string[]
     */
    protected $mitigations = [];

    /**
     * @return string
     */
    public function getFailureReason()
    {
        return $this->failureReason;
    }

    /**
     * @param string $failureReason
     */
    public function setFailureReason($failureReason)
    {
        $this->failureReason = $failureReason;
    }

    /**
     * @return array
     */
    public function getMitigations()
    {
        return $this->mitigations;
    }

    /**
     * @param array $mitigations
     */
    public function setMitigations(array $mitigations)
    {
        $this->mitigations = $mitigations;
    }

    /**
     * @param string $mitigation
     */
    public function addMitigation($mitigation)
    {
        $this->mitigations[] = $mitigation;
    }
}

#
# Start of Flow generated Proxy code
#
/**
 * Class FailedCompilingState
 *
 * Replacement ParsingState used when a template fails to compile.
 * Includes additional reasons why compiling failed.
 * @codeCoverageIgnore
 */
class FailedCompilingState extends FailedCompilingState_Original implements \Neos\Flow\ObjectManagement\Proxy\ProxyInterface {

    use \Neos\Flow\ObjectManagement\Proxy\ObjectSerializationTrait;


    /**
     * Autogenerated Proxy Method
     */
    public function __sleep()
    {
            $result = NULL;
        $this->Flow_Object_PropertiesToSerialize = array();
        unset($this->Flow_Persistence_RelatedEntities);

        $transientProperties = array (
);
        $propertyVarTags = array (
  'failureReason' => 'string',
  'mitigations' => 'array<string>',
  'identifier' => 'string',
  'rootNode' => 'TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\RootNode',
  'nodeStack' => 'array',
  'variableContainer' => 'TYPO3Fluid\\Fluid\\Core\\Variables\\VariableProviderInterface',
  'layoutNameNode' => 'AbstractNode',
  'compilable' => 'boolean',
);
        $result = $this->Flow_serializeRelatedEntities($transientProperties, $propertyVarTags);
        return $result;
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __wakeup()
    {

        $this->Flow_setRelatedEntities();
    }
}
# PathAndFilename: /Applications/MAMP/htdocs/neos-example/Packages/Libraries/typo3fluid/fluid/src/Core/Compiler/FailedCompilingState.php
#